### ISSUE TITLE
Unable to build and run site

### ISSUE THREAD

**Issue by ayushjain01** [zeon-studio/hugoplate#106]
### What is your Hugo Extended Version

v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended windows/amd64

### What is your Go Version

 go1.22.1 windows/amd64

### What is your Node.js Version

v20.11.1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

I followed all the instructions and ran the following commands -
```bash
npm run project-setup
npm install
npm run dev
````

The site does not build and gives the below error -
```bash
Start building sites …
hugo v0.123.8-5fed9c591b694f314e5939548e11cc3dcb79a79c+extended windows/amd64 BuildDate=2024-03-07T13:14:42Z VendorInfo=gohugoio

ERROR POSTCSS: failed to transform "/css/style-lazy.css" (text/css): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Built in 406 ms
Error: error building site: POSTCSS: failed to transform "/css/style.css" (text/css): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps to Reproduce

1. Download the Repository
2. Download and install Go and Hugo extended version
3. Follow instructions to run and build the project

### Code Reproduction URL

https://github.com/ayushjain01/hugoplate-clone

**Comment by jmooring** [comment]
<https://gohugo.io/functions/resources/postcss/>

> If you are a Windows user, and the path to your project contains a space, you must place the PostCSS configuration within the package.json file. See [this example](https://github.com/postcss/postcss-load-config#packagejson) and issue [#7333](https://github.com/gohugoio/hugo/issues/7333).
