### ISSUE TITLE
url vs pageRef

### ISSUE THREAD

**Issue by technosprout** [zeon-studio/hugoplate#107]
### What is your Hugo Extended Version

0.123.8

### What is your Go Version

1.22.1

### What is your Node.js Version

21.7.1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

in the menu template  for internal links one should use pageRef instead of URL

### Steps to Reproduce

menus.en.toml

**Comment by tfsomrat** [comment]
We have updated the menu using pageRef
