### ISSUE TITLE
Making text wrap around (or be next to) images in a single blog page.

### ISSUE THREAD

**Issue by iamsridhar** [zeon-studio/hugoplate#11]
Trying to author blog posts using this template. How can I make text in the blog wrap around (or be next to) images within the body of the content of the blog?

I am embedding images in the blog using the figure short-code. Something like:
{{< figure src="/images/digital-payments-blog/hugoblog_1.png" command="Resize" options="100x" caption="Ditigal payment QR code in a mom-and-pop store" >}}

Thanks!

**Comment by tfsomrat** [comment]
Hi, please follow the implementation guide: https://github.com/gethugothemes/hugo-modules/tree/master/images#shortcode-implementation

you can achieve this functionality with `position:float-left` or `position:float-right`

**Comment by iamsridhar** [comment]
Thanks, works on desktop, but not responsive on mobile.
