### ISSUE TITLE
change images directory to blog/english

### ISSUE THREAD

**Issue by psalphabeta** [zeon-studio/hugoplate#110]
Images are stored under assets/images, how to set the blog/english as the default directory for storing images

**Comment by tfsomrat** [comment]
Hey @psalphabeta, you can't set it as default storage, but you can store image in `english/blog` directory. and change the image calling path, and add `Context` with image partial, it will work. for more info, checkout this doc: https://github.com/gethugothemes/hugo-modules/tree/master/images#image-implementation
