### ISSUE TITLE
Remove hasChildren from menu entry definition in example site

### ISSUE THREAD

**Issue by jmooring** [zeon-studio/hugoplate#111]
### What is your Hugo Extended Version

irrelevant

### What is your Go Version

irrelevant

### What is your Node.js Version

irrelvant

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

`hasChildren` in a menu entry definition doesn't do anything and confuses site authors.

### Steps to Reproduce

https://github.com/zeon-studio/hugoplate/blob/main/exampleSite/config/_default/menus.en.toml#L22

**Comment by tfsomrat** [comment]
@jmooring Thank you.
