### ISSUE TITLE
Remove dark mode script does not remove theme switcher

### ISSUE THREAD

**Issue by Frank3K** [zeon-studio/hugoplate#112]
### What is your Hugo Extended Version

hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended

### What is your Go Version

go version go1.22.1

### What is your Node.js Version

v20.2.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

When running the `remove-darkmode` script, the theme switcher is not removed. 

### Steps to Reproduce

1. Install the theme according to the instructions in the README.
2. Run `yarn run remove-darkmode`.
3. Build the site.
4. Observe that the theme switcher (which enables the user to toggle between light and dark modes) is still present.

### Additional Information

The following things should be removed:

1. The SCSS for the theme-switcher ([src](https://github.com/zeon-studio/hugoplate/blob/feeeab466539e8bc7252e2ecbeb354443cf0fe07/assets/scss/navigation.scss#L66-L87)).
2. The theme-switcher HTML ([src](https://github.com/zeon-studio/hugoplate/blob/feeeab466539e8bc7252e2ecbeb354443cf0fe07/layouts/partials/components/theme-switcher.html)).
3. The use of the partial in the header ([src](https://github.com/zeon-studio/hugoplate/blob/feeeab466539e8bc7252e2ecbeb354443cf0fe07/layouts/partials/essentials/header.html#L126)).
4. The darkmode logo ([src](https://github.com/zeon-studio/hugoplate/blob/feeeab466539e8bc7252e2ecbeb354443cf0fe07/exampleSite/assets/images/logo-darkmode.png)).
5. The darkmode logo reference in params.toml ([src](https://github.com/zeon-studio/hugoplate/blob/feeeab466539e8bc7252e2ecbeb354443cf0fe07/exampleSite/config/_default/params.toml#L6)).
6. Theme switcher config in params.toml ([src](https://github.com/zeon-studio/hugoplate/blob/feeeab466539e8bc7252e2ecbeb354443cf0fe07/exampleSite/config/_default/params.toml#L17-L19)).

**Comment by tfsomrat** [comment]
Hey @Frank3k, thanks for creating this issue. we updated the script. now it will work perfectly.

**Comment by Frank3K** [comment]
Thanks for fixing, appreciated.
