### ISSUE TITLE
Remove unused dns-prefetch links

### ISSUE THREAD

**Issue by jcarnat** [zeon-studio/hugoplate#113]
Hi,

Because I don't need Facebook/Twitter/GitHub links, I removed their entries from `data/social.json`. That does remove the icons from the web pages but the `dns-prefetch` links are still present in the rendered pages. Same goes with Google Analytics, that I don't use.

What is the proper way to remove those from the rendered pages?

Thanks.

**Comment by tfsomrat** [comment]
you can remove prefetch from [here](https://github.com/zeon-studio/hugoplate/blob/main/layouts/partials/essentials/style.html) and google analytics from [here](https://github.com/zeon-studio/hugoplate/blob/main/layouts/partials/essentials/head.html)
