### ISSUE TITLE
Please change the default baseURL

### ISSUE THREAD

**Issue by jmooring** [zeon-studio/hugoplate#116]
### What is your Hugo Extended Version

x

### What is your Go Version

x

### What is your Node.js Version

x

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

x

### Steps to Reproduce

x

### Additional Information

https://github.com/zeon-studio/hugoplate/blob/main/exampleSite/hugo.toml#L3

Please change this to something like `https://example.org/`. I can't count the number of times a config like this has caused problems in the wild.

**Comment by tfsomrat** [comment]
Hey @jmooring, thanks for your concern. If I change the baseURL to something like this, then all the users of this template are forced to change their baseURL to deploy their website. and I have got too many issues about the broken site because they did not change their baseURL. so I choose to use baseURL like this. at least it deploys their site properly.

**Comment by jmooring** [comment]
> all the users of this template are forced to change their baseURL to deploy their website

Which is what they should be doing in the first place.

**Comment by tfsomrat** [comment]
Yes, I can understand. but most of the cases they didn't do it, and create an issue about the site is broken. that's why I choose to use the baseURL as "/". and then I asked the user to use their own baseURL when deploying.

**Comment by jmooring** [comment]
You can obviously do what you want, but this practice is not helpful to the Hugo community at large.

**Comment by tfsomrat** [comment]
Hi, I think about the issue, and came up with a new idea. I have added an announcement to the demo, and it says user needs to change the baseURL, so no one missed the guideline.
![CleanShot 2024-04-17 at 09 31 00](https://github.com/zeon-studio/hugoplate/assets/58769763/72c21938-31ff-44be-b172-27824046496c)

you can also check the live demo here https://hugoplate.netlify.app/

**Comment by rici44** [comment]
Hi. When editing website in dev enviroment, 404.html is working correctly, but when build and upload to webserver it does not snow.
