### ISSUE TITLE
npm run build breaks the website

### ISSUE THREAD

**Issue by vovanukas** [zeon-studio/hugoplate#117]
I have deployed the website using GitHub pages to this url: https://codiblox.com/

When previewing it in VSCode by running npm run dev, the website looks good but when I build the website using npm run build, the website looks weird with 2 logos and big menu items.

 
<img width="1430" alt="image" src="https://github.com/zeon-studio/hugoplate/assets/31879544/2a79c5fd-d2b7-4ddb-83a1-bda9fabad4dc">

<img width="1341" alt="image" src="https://github.com/zeon-studio/hugoplate/assets/31879544/a2e3a1c5-7336-4d4f-9709-72f4b12839eb">

**Comment by tfsomrat** [comment]
You are blocked by CORS policy. try to use baseURL `https://codiblox.com/` instead of `https://www.codiblox.com/`

**Comment by vovanukas** [comment]
Thanks, worked!
