### ISSUE TITLE
Please change the default baseURL

### ISSUE THREAD

**Issue by frjo** [zeon-studio/hugoplate#118]
Please change this to something like `https://example.org/`. In the Hugo forums we get large number of new users that get in to trouble because they keep this example setting.

https://github.com/zeon-studio/hugoplate/blob/a7e20890077bcb42cf0a81cad4b291bba31f5dd0/exampleSite/hugo.toml#L3

**Comment by tfsomrat** [comment]
Hey @frjo, thanks for your concern. It's a duplicate issue of #116, there I was explained why I did this. but still, I'll consider to change the baseURL, can you please share with me some threads about the baseURL issue. it will help me understand, thank you again.

**Comment by frjo** [comment]
Sorry for the duplicate, missed to look.
