### ISSUE TITLE
Site deployed on GitHub pages loses some formatting

### ISSUE THREAD

**Issue by vovanukas** [zeon-studio/hugoplate#119]
After deploying the website on GitHub pages, the site lost some off of formatting/css. To name a few issues I have found:

- Margins feel off
- Bullet lists are gone
- Code blocks are not rounded
- No backticks (') around code snippets. 

This is both seen on mobile and desktop - currently adding the pictures of issues on mobile and I will add the pictures of how it should look like asap.![image](https://github.com/zeon-studio/hugoplate/assets/31879544/14a79760-c850-47d1-a2d1-102acb62351c)

![image](https://github.com/zeon-studio/hugoplate/assets/31879544/c2dc6022-991b-41b4-a6a1-bfeae81c3b00)

**Comment by tfsomrat** [comment]
Hey @vovanukas, use purgeCSS v5 instead of v6 https://github.com/vovanukas/hugoplate/blob/35a4aa19ecc72173c8aaf920fa627bf38624c713/package.json#L22C5-L22C45
