### ISSUE TITLE
Resizing cover/header image for a blog page

### ISSUE THREAD

**Issue by iamsridhar** [zeon-studio/hugoplate#12]
There are two issues with the cover image for the blog page. 
1. It appears huge - is there a way to resize through the front-matter params?
2. Different blog cards in the list view have different cover image sizes. this should be consistently the same.

Here's front matter I am using

---
title: "India's digital payments revolution"
meta_title: "How India has gone digital at breakneck speed"
description: "One of the world's biggest success stories"
date: 2022-07-21T05:00:00Z
image: "/images/digital-payments-blog/hugoblog_1.png"
---

**Comment by tfsomrat** [comment]
Hi, since it's a starter template, there are no params to customize it. you have to customize the markup to achieve this. thanks
