### ISSUE TITLE
Reload the searchindex.json file twice.

### ISSUE THREAD

**Issue by Remyy-y** [zeon-studio/hugoplate#121]
### What is your Hugo Extended Version

0.123.4

### What is your Go Version

1.22.0

### What is your Node.js Version

20.12.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

When the js index is very large, it will make the website load very slowly.

### Steps to Reproduce

Your display page also has this issue.

### Additional Information

![image](https://github.com/zeon-studio/hugoplate/assets/84855700/e4db7d55-7d26-4756-8db3-a1e0d8838084)

**Comment by tfsomrat** [comment]
can you share your repository?

**Comment by Remyy-y** [comment]
![image](https://github.com/zeon-studio/hugoplate/assets/84855700/51613144-c79c-4ad9-804f-e72e2ccde52b)
https://zeon.studio/preview?project=hugoplate

**Comment by Remyy-y** [comment]
> can you share your repository?

![image](https://github.com/zeon-studio/hugoplate/assets/84855700/d9c1dcde-5099-4860-a595-a5a1519a70d9)
https://zeon.studio/preview?project=hugoplate

**Comment by tfsomrat** [comment]
Hey @Remyy-y, thank you for finding this. we have updated our search module, now you can update your modules by running `npm run update-modules`, it will solve the issue.
