### ISSUE TITLE
Hero image source

### ISSUE THREAD

**Issue by jkhalaf-gm** [zeon-studio/hugoplate#123]
Hello

This isn't a code issue. But I thought I'd ask here as I couldn't see where else to ask.

Where did you get the hero image from?

![image](https://github.com/zeon-studio/hugoplate/assets/168232979/36751faa-73ab-4c60-91e4-1a7b32f698af)

I am looking for images in the same style. If you could link us to the source or artist that created them, that would be greatly appreciated.

Thanks

**Comment by tfsomrat** [comment]
This image was probably downloaded from freepik, and then we modified it to match the theme style.
