### ISSUE TITLE
Your file couldn't be accessed

### ISSUE THREAD

**Issue by perfectdarkmode1** [zeon-studio/hugoplate#124]
### What is your Hugo Extended Version

hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended linux/amd64 BuildDate=2024-03-20T11:40:10Z VendorInfo=gohugoio

### What is your Go Version

go version go1.22.2 linux/amd64

### What is your Node.js Version

v20.12.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

After going through the site setup steps, I run `npm run dev`, then go to the local host site generated in the output, I should see the example site. 

### Steps to Reproduce

1. Run command `npm run dev`
2. Go to //localhost:1313/ in a web browser

### Code Reproduction URL

no current repo

### Additional Information

I get "Your file couldn't be accessed" instead of the example site.

**Comment by tfsomrat** [comment]
Hey @perfectdarkmode1, Run it again, and go to http://localhost:1313

**Comment by perfectdarkmode1** [comment]
Hey that worked! Thank you. Glad it was so simple lol
