### ISSUE TITLE
when running in provided devcontainer npm run dev errors out 

### ISSUE THREAD

**Issue by preston-bernstein** [zeon-studio/hugoplate#128]
### What is your Hugo Extended Version

v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended linux/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio

### What is your Go Version

go1.21.4 linux/amd64

### What is your Node.js Version

v20.13.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

When I run npm run dev in a terminal within the docker container created by the .devcontainer,
then I expect that the site builds properly

### Steps to Reproduce

1. Open hugoplate in vscode
2. Open in docker container as prompted
3.  run npm run dev in terminal

It hangs on
Start building sites … 
hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended linux/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio

and then it errors out

ERROR render of "section" failed: "/workspaces/hugoplate/themes/hugoplate/layouts/_default/baseof.html:15:7": execute of template failed: template: _default/list.html:15:7: executing "_default/list.html" at <partialCached "essentials/style.html" .>: error calling partialCached: partial "essentials/style.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
ERROR render of "page" failed: "/workspaces/hugoplate/themes/hugoplate/layouts/_default/baseof.html:15:7": execute of template failed: template: _default/single.html:15:7: executing "_default/single.html" at <partialCached "essentials/style.html" .>: error calling partialCached: partial "essentials/style.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
ERROR render of "term" failed: "/workspaces/hugoplate/themes/hugoplate/layouts/_default/baseof.html:15:7": execute of template failed: template: _default/taxonomy.html:15:7: executing "_default/taxonomy.html" at <partialCached "essentials/style.html" .>: error calling partialCached: partial "essentials/style.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
Built in 41927 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/workspaces/hugoplate/themes/hugoplate/layouts/_default/baseof.html:15:7": execute of template failed: template: _default/single.html:15:7: executing "_default/single.html" at <partialCached "essentials/style.html" .>: error calling partialCached: partial "essentials/style.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.

### Code Reproduction URL

github.com/zeon-studio/hugoplate.git

### Additional Information

I am running on Windows

An additional issue I have discovered is that even inside the devcontainer terminal, it is using my system's node version and not the version explicitly declared in the Dockerfile.

**Comment by keesfluitman** [comment]
I get the same errors.

**Comment by preston-bernstein** [comment]
> did you run `npm run project-setup` before running `npm run dev`?

Yes, I did

**Comment by keesfluitman** [comment]
Anyonr got an idea? Ill try it on a different machine. But id love to use this theme.

**Comment by preston-bernstein** [comment]
I propose removing the .devcontainer and anything else related to it from
the main branch for now, until this issue is resolved.

**Comment by preston-bernstein** [comment]
> Anyonr got an idea? Ill try it on a different machine. But id love to use this theme.

You just need not to open it in the devcontainer, and use your local environment.

**Comment by keesfluitman** [comment]
> > Anyonr got an idea? Ill try it on a different machine. But id love to use this theme.
> 
> You just need not to open it in the devcontainer, and use your local environment.

Unfortunately i get this error on a ubuntu vm. Not in a devcontainer. But ill try debugging

**Comment by preston-bernstein** [comment]
@keesfluitman the latest build does fix the .devcontainer issue. Now it reveals an issue supposedly with the css (?) in the exampleSite. Opening related issue.

**Comment by keesfluitman** [comment]
> @keesfluitman the latest build does fix the .devcontainer issue. Thanks @tfsomrat

i noticed that the build just takes very long, and so times out. When building, it works fine. So I just need to add to the timeout.
