### ISSUE TITLE
Add basic js testing [enhancement]

### ISSUE THREAD

**Issue by preston-bernstein** [zeon-studio/hugoplate#129]
### What is your Hugo Extended Version

hugo v0.126.1-3d40aba512931031921463dafc172c0d124437b8+extended windows/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=gohugoio

### What is your Go Version

go1.22.3 windows/amd64

### What is your Node.js Version

v21.6.2

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

When I use hugoplate as a developer
Then I want to see tests
To further ensure quality of code and code-completeness of starter project

### Steps to Reproduce

Clone the project and run tests to verify javascript code,
and to use as a template to build off of for users of this repository.

### Additional Information

I have introduced js testing infrastructure in my project built off of hugoplate. I can introduce it into hugoplate if we would like to.

**Comment by tfsomrat** [comment]
Hey @preston-bernstein, Please create a PR. If it does make sense, I'll merge it. thanks.
