### ISSUE TITLE
CSS broken in .devcontainer example site even after changing baseurl

### ISSUE THREAD

**Issue by preston-bernstein** [zeon-studio/hugoplate#131]
### What is your Hugo Extended Version

hugo v0.126.1-3d40aba512931031921463dafc172c0d124437b8+extended linux/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=gohugoio

### What is your Go Version

go version go1.22.3 linux/amd64

### What is your Node.js Version

v20.13.1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

When I open repo in .devcontainer
And after .devcontainer finishes setting up
And then I change baseUrl (eg: to https://examplesite.com)
Then I open localhost:1313
Then I expect css to have loaded properly

### Steps to Reproduce

1. Open latest build in vscode, and use .devcontainer
2. Change baseUrl in exampleSite/hugo.toml to https://examplesite.com
3. Open localhost:1313 in browser and see broken css

![toda](https://github.com/zeon-studio/hugoplate/assets/77080227/0b1721fb-1e40-4249-adea-020c773b3a81)

**Comment by tfsomrat** [comment]
Hey @preston-bernstein, I couldn't reproduce this issue. it seems to work perfectly. can you try to close the Hugo server (`ctrl+c`) and run it again (`yarn dev:example`)?
