### ISSUE TITLE
Error postCSS

### ISSUE THREAD

**Issue by acorbesier** [zeon-studio/hugoplate#132]
### What is your Hugo Extended Version

hugo v0.126.1-3d40aba512931031921463dafc172c0d124437b8+extended windows/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=gohugoio

### What is your Go Version

go version go1.22.3 windows/amd64

### What is your Node.js Version

v20.13.1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

I expected the website to run but instead i get the following error.

> 

### Steps to Reproduce

I followed the steps from the guide.

### Additional Information

PS C:\Users\ArthurCorbesier\OneDrive - ksdiest.be\2023-2024\#GIP\GIP-Website\hugoplate> npm run dev

> hugoplate@1.15.1 dev
> hugo server

Watching for changes in C:\Users\ArthurCorbesier\OneDrive - ksdiest.be\2023-2024\#GIP\GIP-Website\hugoplate\{assets,content,data,hugo_stats.json,i18n,package.json,postcss.config.js,tailwind.config.js,themes}
Watching for config changes in C:\Users\ArthurCorbesier\OneDrive - ksdiest.be\2023-2024\#GIP\GIP-Website\hugoplate\hugo.toml, C:\Users\ArthurCorbesier\OneDrive - ksdiest.be\2023-2024\#GIP\GIP-Website\hugoplate\config\_default, C:\Users\ArthurCorbesier\OneDrive - ksdiest.be\2023-2024\#GIP\GIP-Website\hugoplate\config\development, C:\Users\ArthurCorbesier\OneDrive - ksdiest.be\2023-2024\#GIP\GIP-Website\hugoplate\go.mod
Start building sites …
hugo v0.126.1-3d40aba512931031921463dafc172c0d124437b8+extended windows/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=gohugoio

ERROR POSTCSS: failed to transform "/css/style-lazy.css" (text/css): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Built in 622 ms
Error: error building site: POSTCSS: failed to transform "/css/style.css" (text/css): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tfsomrat** [comment]
Hey @acorbesier, is this a space into this folder name `OneDrive - ksdiest.be`?

**Comment by acorbesier** [comment]
I don't understand what you mean, OneDrive - ksdiest.be is just a folder on my pc for my onedrive. I also tried installing on Linux Ubuntu but i got the same error that the file is missing.

**Comment by tfsomrat** [comment]
If your root folder name contains space, it won't work. And, you may have missed a step when installing. follow this video https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#-still-confused-watch-a-quick-video

**Comment by acorbesier** [comment]
Thank you, now it's working perfectly. Weird that you can't have a space in the folder name.
