### ISSUE TITLE
Light/Dark button flickers when a menu item is clicked

### ISSUE THREAD

**Issue by technosprout** [zeon-studio/hugoplate#135]
### What is your Hugo Extended Version

0.126.1+extended

### What is your Go Version

1.22.3

### What is your Node.js Version

22.2.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

- Light/ dark button flickers when menu items are clicked; it switches back and forth to its current state.
- Format for the page layouts cause the menu to flicker

### Steps to Reproduce

1. Click any menu item, the dark/light button flickers
2. Click any menu item the layout of the page jumps instead of a smooth transition

**Comment by tfsomrat** [comment]
Hey @technosprout, We have finally addressed the issue. You can check it now. Thanks
