### ISSUE TITLE
Navigation ignores external URLs.

### ISSUE THREAD

**Issue by tuxpizza** [zeon-studio/hugoplate#136]
Seems like the navigation configuration under menus.en.toml do not allow anything _except_ subdirectories. This is very un-ideal as it completely limits the use of the navigation bar.

It totally ignores any external links or URI fragments (which none seem to exist for the features sections on the main page anyways).

**Comment by tfsomrat** [comment]
Hey @tuxpizza, you need to use `url` instead of `pageRef` to use an external link in menu. for example
```
[[main]]
name = "Google"
url = "https://google.com"
weight = 2
```
