### ISSUE TITLE
unsupported redirect to value "/en/404.html"

### ISSUE THREAD

**Issue by SZStgt** [zeon-studio/hugoplate#137]
### What is your Hugo Extended Version

hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1

### What is your Go Version

go version go1.22.3 linux/amd64

### What is your Node.js Version

v20.14.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

`npm run dev ` runs without issues and starts a server

### Steps to Reproduce

1. Follow the Video  
2. Download zip
3. Unpackzip
4. `npm run project-setup`
5. `npm install`
6. `npm run dev`
7. Error: unsupported redirect to value "/en/404.html" in server config; currently this must be either a remote destination or a local folder, e.g. "/blog/" or "/blog/index.html"

### Additional Information

After disabling  [[redirects]] in server.toml, `npm run dev` outputs a List of warnings and then the following Errors:

Error: Error building site: "/home/liviu/hugo/hugoplate/hugoplate-main/content/english/pages/elements.md:230:1": failed to render shortcode "gallery": failed to process shortcode: execute of template failed: template: shortcodes/gallery.html:31:11: executing "shortcodes/gallery.html" at <partial "image-pipe.html" (dict "Context" $scratch "Height" $height "Width" $width "Command" $command "Webp" $webp "Image" $image "Option" $option "Zoomable" $zoomable "Resize" $resize)>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/gallery-slider@v0.0.0-20240525031707-f23b0cd94862/layouts/partials/image-pipe.html:39:22": execute of template failed: template: partials/image-pipe.html:39:22: executing "partials/image-pipe.html" at <add>: wrong number of args for add: want 2 got 3

**Comment by tfsumon** [comment]
Hi @SZStgt,

Thank you for your report. The errors you're encountering are likely due to using Hugo v0.92.2, while the template requires at least v0.124.1. Please update your Hugo installation to the latest version.

Let me know if you need further assistance!
