### ISSUE TITLE
Dark/Light Mode Images Outside Header/Footer

### ISSUE THREAD

**Issue by espinlove** [zeon-studio/hugoplate#143]
Ideally, I would like to be able to include images in the body of the website that are dependant on the dark/light mode.

At the very least, I would like to be able to include another dark/light mode image in the footer as well as have a dark/light mode banner image.

My apologies, I am a relative novice when it comes to this kind of website development so I'm not yet able to describe problems using technical terminology...

I guess this comes down to three things:

Problem 1:
Using existing layout .html definitions - My first thought was to use something similar to header.html where the navbar {{ partial "logo" }} is used. I assume this partial is something inbuilt but I can't find any useful documentation on the usage (other than amending the logo.html which doesn't exist here).

Problem 2:
Determining dark/light mode status - I have also found documentation on this issue but it is dependant on the user's system setting as opposed to the dark/light mode "switch". I understand that, for example, in the page-header.html the class="from-body to-theme-light dark:from-darkmode-body dark:to-darkmode-theme-light ..... etc" is how it is determined. However, it seems to be implemented quite differently than other dark/light switching.

Problem 3:
Generic setting - I can see that it is possible to have dark/light mode images in general. I can't see how this would be done in the body text, though the above 2 points probably demonstrate why!

Thank you, in advance, for any help.

**Comment by tfsomrat** [comment]
Hey @espinlove, Sorry for the late reply, you can add a class to handle this case. For light-mode images, you can add `img-light` and for dark-mode, use `img-dark` class. 

here is an example
```
{{ partial "image" (dict "Src" "/images/img-light.png" "Class" "img-light") }}
{{ partial "image" (dict "Src" "/images/img-dark.png" "Class" "img-dark") }}
```
