### ISSUE TITLE
flags for language switcher

### ISSUE THREAD

**Issue by psclplg** [zeon-studio/hugoplate#144]
I'd like to see the language switcher using flag icons/images instead of text.
I was unable to make the required changes within the code on my own and would like to request for help/solution.

I'd be pleased to help/assist as much as I can.

**Comment by tfsomrat** [comment]
Hey @psclplg, we only use the GitHub issues to identify product bugs. If you need any customization services, please contact us here https://zeon.studio/estimate-project.
