### ISSUE TITLE
pageRef to page fail

### ISSUE THREAD

**Issue by skapin** [zeon-studio/hugoplate#146]
### What is your Hugo Extended Version

0.134.1

### What is your Go Version

1.18.1

### What is your Node.js Version

20

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

Naviating from menu to /elements (or any other page) should works, but it generate a link to '/' instead. 

Accessing /elements/ directly in webbrowser works, but it's the link generated in the index that fail.

pageRef is correct in menus.en.toml

### Steps to Reproduce

1. install fresh install
2. yarn run dev
3. click on element from menu bar
4. it fails
5. try by adding /elements/ to url. it works

**Comment by psclplg** [comment]
I experienced the same behaviour with other sites from the pages folder. 
This can be solved by moving files from pages folder up to the language specific content folder.
Worked for me running the command "hugo server".
