### ISSUE TITLE
Should we add git info to the footer ?

### ISSUE THREAD

**Issue by gedw99** [zeon-studio/hugoplate#148]
```sh) --enableGitInfo
```

But I dont see it anywhere in the Web GUI of exampleSite or Hugo modules.. Maybe I missed it.

https://gohugo.io/methods/page/gitinfo/ explains the meta ...

Seems to me that it could be cool to add this to the footer ?

**Comment by tfsomrat** [comment]
I didn't get your point. can you explain what is the issue here?

**Comment by tfsomrat** [comment]
It's a startup template, and you must build your own functionality. thanks
