### ISSUE TITLE
ARG / ENV to turn off Hugo nag screen when --baseURL set

### ISSUE THREAD

**Issue by gedw99** [zeon-studio/hugoplate#149]
baseURL args works, but the Nag screen is still there...

```sh
hugo server --baseURL=$(HUGO_RUN_BASE_URL) --enableGitInfo --disableFastRender --navigateToChanged --templateMetrics --templateMetricsHints --watch --forceSyncStatic -e production --minify
```

But it does not get rid of the nag screen at the top of each web page which says:

"
You must replace the baseURL in hugo.toml file when deploying, you can manage this announcement from the params.toml file.
"

Doing this in the config seems wrong.

It's ops time when you pick a baseURL and also want to turn off the Nag screen. Hence we need a way to turn this off via ARGS / ENV, and not config.

 --disableBrowserError does not turn it off. Seems silly since I set a baseURL 

Anyone know ? 

then we can update the code of:

```sh
hugo server --baseURL=$(HUGO_RUN_BASE_URL) --enableGitInfo --disableFastRender --navigateToChanged --templateMetrics --templateMetricsHints --watch --forceSyncStatic -e production --minify
```

**Comment by tfsomrat** [comment]
Hey @gedw99, It's an `Announcement / Hellobar` and could not be managed with Hugo Flags. You have to turn it off from the `params.toml` file. Also you can use this bar for any type of notice or anything that you want to show your visitor.
