### ISSUE TITLE
npm run dev fails with this error - Error: error building site: process: readAndProcessContent: "/home/<USER>/hugoplate/content/english/404.html:1:1": unmarshal failed: invalid character '{' looking for beginning of object key string

### ISSUE THREAD

**Issue by ll3N1GmAll** [zeon-studio/hugoplate#155]
### What is your Hugo Extended Version

0.138.0-ad82998d54b3f9f8c2741b67356813b55b3134b9+extended

### What is your Go Version

go1.23.3 linux/amd64

### What is your Node.js Version

22.11.0

### What is your Operating System

ubuntu / zorin

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

hugo -D server starts

### Steps to Reproduce

clone hugoplate repo, cd into directory, run first 3 commands on github instructions (project setup, install deps, dev command) sections.

### Additional Information

Running "npm run dev" fails with this error - "Error: error building site: process: readAndProcessContent: "/home/<USER>/hugoplate/content/english/404.html:1:1": unmarshal failed: invalid character '{' looking for beginning of object key string"

**Comment by tfsomrat** [comment]
Hey @ll3N1GmAll, we have updated the theme, hopefully this issue is resolved. please check it and let me know. thanks

**Comment by tfsomrat** [comment]
please follow this video and start from scratch
https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#-still-confused-watch-a-quick-video

**Comment by sachhu** [comment]
I am also getting the same error while doing npm run dev

solo@shekhar-X555LF:~/projects/kk/hugoplate$ npm run project-setup

> hugoplate@2.0.4 project-setup
> node ./scripts/projectSetup.js

solo@shekhar-X555LF:~/projects/kk/hugoplate$ npm install 

added 41 packages, and audited 42 packages in 34s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
solo@shekhar-X555LF:~/projects/kk/hugoplate$ npm run dev

> hugoplate@2.0.4 dev
> hugo server

hugo: downloading modules …
hugo: collected modules in 4020 ms
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2025/03/06 02:24:21 found no layout file for "HTML" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
Error: Error building site: "/home/solo/projects/kk/hugoplate/content/english/pages/elements.md:240:1": failed to render shortcode "gallery": failed to process shortcode: execute of template failed: template: shortcodes/gallery.html:31:11: executing "shortcodes/gallery.html" at <partial "image-pipe.html" (dict "Context" $scratch "Height" $height "Width" $width "Command" $command "Webp" $webp "Image" $image "Option" $option "Zoomable" $zoomable "Resize" $resize)>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/gallery-slider@v0.0.0-20250302032254-95e856a2b3fc/layouts/partials/image-pipe.html:39:22": execute of template failed: template: partials/image-pipe.html:39:22: executing "partials/image-pipe.html" at <add>: wrong number of args for add: want 2 got 3
Built in 234 ms

Please help

**Comment by tfsomrat** [comment]
thats because you are using hugo v0.92.2+extended, you need to update your hugo version to 0.145+
