### ISSUE TITLE
Error after first template run

### ISSUE THREAD

**Issue by LukasLokajicek** [zeon-studio/hugoplate#157]
### What is your Hugo Extended Version

hugo v0.139.2 windows/amd64 BuildDate=unknown

### What is your Go Version

go version go1.23.3 windows/amd64

### What is your Node.js Version

v22.11.0

### What is your Operating System

Windows 11

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

No errors when there are no changes in the initial template.

### Steps to Reproduce

When:
npm run project-setup
npm install
npm run dev

Then:

ERROR render of "section" failed: "C:\Users\<User_name>\IdeaProjects\hugoplate\themes\hugoplate\layouts\_default\baseof.html:38:7": execute of template failed: template: authors/list.html:38:7: executing "authors/list.html" at <partial "essentials/header.html" .>: error calling partial: "C:\Users\<User_name>\IdeaProjects\hugoplate\themes\hugoplate\layouts\partials\essentials\header.html:8:11": execute of template failed: template: partials/essentials/header.html:8:11: executing "partials/essentials/header.html" at <partial "logo">: error calling partial: "C:\Users\<User_name>\AppData\Local\hugo_cache\modules\filecache\modules\pk
g\mod\github.com\gethugothemes\hugo-modules\images@v0.0.0-20240925042433-d2b5d05977e8\layouts\partials\logo.html:83:33": execute of template failed: template: partials/logo.html:83:33: executing "partials/logo.html" at <$logo.Resize>: error calling Resize: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR render of "home" failed: "C:\Users\<User_name>\IdeaProjects\hugoplate\themes\hugoplate\layouts\_default\baseof.html:38:7": execute of template failed: template: index.html:38:7: executing "index.html" at <partial "essentials/header.html" .>: error calling partial: "C:\Users\<User_name>\IdeaProjects\hugoplate\theme
s\hugoplate\layouts\partials\essentials\header.html:8:11": execute of template failed: template: partials/essentials/header.html:8:11: executing "partials/essentials/header.html" at <partial "logo">: error calling partial: "C:\Users\<User_name>\AppData\Local\hugo_cache\modules\filecache\modules\pkg\mod\github.com\
gethugothemes\hugo-modules\images@v0.0.0-20240925042433-d2b5d05977e8\layouts\partials\logo.html:83:33": execute of template failed: template: partials/logo.html:83:33: executing "partials/logo.html" at <$logo.Resize>: error calling Resize: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR render of "section" failed: "C:\Users\<User_name>\IdeaProjects\hugoplate\themes\hugoplate\layouts\_default\baseof.html:38:7": execute of template failed: template: about/list.html:38:7: executing "about/list.html" at <partial "essentials/header.html" .>: error calling partial: "C:\Users\<User_name>\IdeaProjects\hu
goplate\themes\hugoplate\layouts\partials\essentials\header.html:8:11": execute of template failed: template: partials/essentials/header.html:8:11: executing "partials/essentials/header.html" at <partial "logo">: error calling partial: "C:\Users\<User_name>\AppData\Local\hugo_cache\modules\filecache\modules\pkg\mo
d\github.com\gethugothemes\hugo-modules\images@v0.0.0-20240925042433-d2b5d05977e8\layouts\partials\logo.html:83:33": execute of template failed: template: partials/logo.html:83:33: executing "partials/logo.html" at <$logo.Resize>: error calling Resize: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR render of "404" failed: "C:\Users\<User_name>\IdeaProjects\hugoplate\themes\hugoplate\layouts\_default\baseof.html:38:7": execute of template failed: template: 404.en.html:38:7: executing "404.en.html" at <partial "essentials/header.html" .>: error calling partial: "C:\Users\<User_name>\IdeaProjects\hugoplate\them
es\hugoplate\layouts\partials\essentials\header.html:8:11": execute of template failed: template: partials/essentials/header.html:8:11: executing "partials/essentials/header.html" at <partial "logo">: error calling partial: "C:\Users\<User_name>\AppData\Local\hugo_cache\modules\filecache\modules\pkg\mod\github.com
\gethugothemes\hugo-modules\images@v0.0.0-20240925042433-d2b5d05977e8\layouts\partials\logo.html:83:33": execute of template failed: template: partials/logo.html:83:33: executing "partials/logo.html" at <$logo.Resize>: error calling Resize: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
ERROR TOCSS: failed to transform "/scss/main.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS with transpiler set to 'libsass'.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 4281 ms
Error: error building site: render: failed to render pages: render of "page" failed: "C:\Users\<User_name>\IdeaProjects\hugoplate\themes\hugoplate\layouts\_default\baseof.html:38:7": execute of template failed: template: authors/single.html:38:7: executing "authors/single.html" at <partial "essentials/header.html"
 .>: error calling partial: "C:\Users\<User_name>\IdeaProjects\hugoplate\themes\hugoplate\layouts\partials\essentials\header.html:8:11": execute of template failed: template: partials/essentials/header.html:8:11: executing "partials/essentials/header.html" at <partial "logo">: error calling partial: "C:\Users\luka
s\AppData\Local\hugo_cache\modules\filecache\modules\pkg\mod\github.com\gethugothemes\hugo-modules\images@v0.0.0-20240925042433-d2b5d05977e8\layouts\partials\logo.html:83:33": execute of template failed: template: partials/logo.html:83:33: executing "partials/logo.html" at <$logo.Resize>: error calling Resize: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information

**Comment by tfsomrat** [comment]
Hey @LukasLokajicek, That's because you are not using the Hugo extended version. Install the hugo extended version and the issue will resolve https://gohugo.io/installation/windows/#winget

**Comment by LukasLokajicek** [comment]
Thank you @tfsomrat, you are right! I have the wrong PATH variable.
