### ISSUE TITLE
Incorrect link of page translations

### ISSUE THREAD

**Issue by TehoorMarjan** [zeon-studio/hugoplate#162]
### What is your Hugo Extended Version

0.139.3

### What is your Go Version

1.23

### What is your Node.js Version

23.3.0

### What is your Operating System

Manjaro Linux

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

Selecting a language in the language-switcher dropdown in the navbar should direct to the proper translated page.

### Steps to Reproduce

1. Create a hugoplate website
2. Configure a language and write 2 copies on the same post for 2 different languages
3. Make the posts have different slugs (either by specific section names or by different slug name) but use the translation key to link them
4. Changing language from one page will lead to a 404 error

### Additional Information

Hi there,

sorry, I feel a bit lazy to open a full pull-request. Hugo provides tools to link the translations of the same article together, even if the slugs are different (in general because they are translated). From what I could see, the current code only exchanges the language token at the beginning of the path, but this is not sufficient. Here is a modified version of `layouts/partials/components/language-switcher.html`.

```html
<!-- Language List -->
{{ if hugo.IsMultilingual }}
  {{ $class := .Class }}
  {{ $context := .Context }}
  {{ $pageLang := $context.Lang }}
  {{ $pageTranslations := newScratch }}
  {{/* First, fill all translations of the Home page (failsafe) */}}
  {{ range site.Home.AllTranslations }}
    {{ $pageTranslations.Set .Language.Lang .Permalink }}
  {{ end }}
  {{/* Second, if a translation exists for the current page for the target language, replace failsafe */}}
  {{ range $context.AllTranslations }}
    {{ $pageTranslations.Set .Language.Lang .Permalink }}
  {{ end }}

  <select class="{{ $class }}" onchange="location = this.value">
    {{ range site.Languages }}
      {{/* Fill the dropdown with all known languages */}}
      {{ $link := $pageTranslations.Get .Lang }}
      {{ if $link }}
        <option
          id="{{ .Lang }}"
          value="{{ $link }}"
        {{ if eq .Lang $pageLang }}
          selected
        {{ end }}
          >
          {{ .LanguageName }}
        </option>
      {{ else }}
        {{/* if we can't safely redirect the user to the translated page or at least to translated home, discard the language from options */}}
      {{ end }}
    {{ end }}
  </select>
{{ end }}
```
The idea is to fill the dropdown with links to the translated page, ordered by the weight given to each languages. If there isn't a translation for the specific language for the current page, then as a fallback, it will link to the homepage of the website in the desired language. If ever the homepage for that language doesn't even exist (strange in practice but possible in theory), then the language isn't added to the dropdown. This is done so that on any page, the user can see and select all available languages of the website, even if it is on a particular page that isn't translated. The code for example properly links

http://localhost:1313/en/posts/2024/12/manjaro-with-system-wide-encryption-and-btrfs/ (en)
to
http://localhost:1313/fr/articles/2024/12/manjaro-avec-btrfs-et-le-chiffrement-du-systeme-entier/ (fr)

(will update preview when website is up with new theme)

**Comment by tfsomrat** [comment]
Hey @TehoorMarjan, Thanks for your help. I have updated the theme.
