### ISSUE TITLE
Best practice for blog/post images

### ISSUE THREAD

**Issue by iamsridhar** [zeon-studio/hugoplate#17]
What is the best practice for storing images for (a) posts (b) site-specific images like those for 404 or other pages? More of a learning question for me, but should images be bundled with posts in the content/english/blog directory? And if so, how do you refer to them (relative path wise)? Where should other pages images go?

**Comment by tfsomrat** [comment]
you can store your image in `content` `static` and `assets` folders. it's your choice where you actually wanted to store it. Or if you are confused about this, you can discuss it on https://discourse.gohugo.io/
