### ISSUE TITLE
Name attribute for Airform.io

### ISSUE THREAD

**Issue by rickdkk** [zeon-studio/hugoplate#24]
Hi,

I couldn't get the contact form to work with Airflow. If I filled in the form I would receive an empty email. The documentation of Airflow states that "All input, select, textarea elements within your form should have a name attribute.".

After I added a name attribute to the layouts/contact/list.html input areas I was able to see the output after receiving an email.

Best,
rickdkk

**Comment by tfsomrat** [comment]
hey @rickdkk 

Thanks for your concern. we have fixed it. please download the latest version and enjoy.
