### ISSUE TITLE
Button action to download a file

### ISSUE THREAD

**Issue by walidbou6** [zeon-studio/hugoplate#26]
I'm trying to to use a button to download a PDF file in my assets folder use it like following:

button:
    enable: true
    label: "get my resume here"
    link: "/pdfs/walid_bousseta_EN.pdf"

but that doesn't work, it's just gives me a 404 error page. is there another way to do so, please could you share with us? and thank you for this wonderful template

**Comment by tfsomrat** [comment]
Hey @walidbou6 

Sorry to hear that. You should put your PDF in the static folder, and then you can do it.

**Comment by walidbou6** [comment]
I have put the pdf in the following path;
/assets/pdfs/walid_bousseta_EN.pdf

I also tried puting it in the data folder that just gived me an error can't load the pdf format

as well created a static folder at the following structure
|--data
|--themes
|--static
|----|--pdfs
|----|-----|--walid_bousseta_EN.pdf
| --.gitignore
|--...
and use the following script:

button:
  enable: true
  label: "get my resume here"
  link: "static/pdfs/walid_bousseta_EN.pdf"

still not working, getting a 404 error

**Comment by walidbou6** [comment]
I did still nothing same error

**Comment by somratpro** [comment]
@walidbou6 
did you tried like this `link: "pdfs/walid_bousseta_EN.pdf"`?

**Comment by ElioDiNino** [comment]
I got this working by creating a static folder and linking as follows:

|--static
|----|--pdfs
|----|-----|--example.pdf

Link: `/pdfs/example.pdf`
