### ISSUE TITLE
Deploy Site On CentOS

### ISSUE THREAD

**Issue by LE2031** [zeon-studio/hugoplate#28]
I renamed the public folder to Hugoplate_Public , then deployed it to a CentOS server, and when I open it, the page format is messed up, is there a problem with the settings there?

Note: I have no problem with the npm run dev command when testing locally.

**Comment by tfsomrat** [comment]
Hey @LE2031 

we only use the `Issues` for themes issues. and this is not a theme issue. If you need any help to deploy your site on a specific platform, you can take our service [Paid] at https://zeon.studio/contact

**Comment by LE2031** [comment]
OK. Thanks for your reply.
---- Replied Message ----
| From | ***@***.***> |
| Date | 08/23/2023 11:07 |
| To | zeon-studio/hugoplate ***@***.***> |
| Cc | 一成 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [zeon-studio/hugoplate] Deploy Site On CentOS (Issue #28) |

Hey @LE2031

we only use the Issues for themes issues. and this is not a theme issue. If you need any help to deploy your site on a specific platform, you can take our service [Paid] at https://zeon.studio/contact

**Comment by LE2031** [comment]
Add: I found out later that there is something wrong with the baseURL setting in my hugo.toml, after adjusting the format, it's fine, the format must be: http(s)://domain(ip)/
