### ISSUE TITLE
I have tried to install this theme 20 times...

### ISSUE THREAD

**Issue by jasonstetson** [zeon-studio/hugoplate#29]
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 3095ms.
(base) PS C:\Windows\system32> cd "C:\Hjemmsider\hugoplate-main"
(base) PS C:\Hjemmsider\hugoplate-main> npm run project-setup

> hugoplate@1.7.4 project-setup
> node ./scripts/projectSetup.js

(base) PS C:\Hjemmsider\hugoplate-main> npm install
>>

added 146 packages, and audited 147 packages in 29s

28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
(base) PS C:\Hjemmsider\hugoplate-main> npm run dev
>>

> hugoplate@1.7.4 dev
> hugo server

hugo: collected modules in 592 ms
Watching for changes in C:\Hjemmsider\hugoplate-main\{assets,content,data,hugo_stats.json,i18n,package.json,postcss.config.js,tailwind.config.js,themes}
Watching for config changes in C:\Hjemmsider\hugoplate-main\hugo.toml, C:\Hjemmsider\hugoplate-main\config\_default, C:\Hjemmsider\hugoplate-main\go.mod
Start building sites …
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended windows/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio

Built in 5786 ms
Error: error building site: POSTCSS: failed to transform "css/style.css" (text/css): SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at decodeUnicode (C:\Hjemmsider\hugoplate-main\tailwind.config.js:11:15)
    at C:\Hjemmsider\hugoplate-main\tailwind.config.js:23:18
    at evalModule (C:\Hjemmsider\hugoplate-main\node_modules\jiti\dist\jiti.js:1:255202)
    at jiti (C:\Hjemmsider\hugoplate-main\node_modules\jiti\dist\jiti.js:1:253130)
    at C:\Hjemmsider\hugoplate-main\node_modules\tailwindcss\lib\lib\load-config.js:37:30
    at loadConfig (C:\Hjemmsider\hugoplate-main\node_modules\tailwindcss\lib\lib\load-config.js:39:6)
    at getTailwindConfig (C:\Hjemmsider\hugoplate-main\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:71:116)
    at C:\Hjemmsider\hugoplate-main\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:100:92
    at C:\Hjemmsider\hugoplate-main\node_modules\tailwindcss\lib\processTailwindFeatures.js:48:11
(base) PS C:\Hjemmsider\hugoplate-main>

**Comment by chark1es** [comment]
Make sure you install GO and prettify before you run the project setup

**Comment by jasonstetson** [comment]
prettify??

**Comment by tfsomrat** [comment]
Did you check out the [prerequisites](https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#%EF%B8%8F-prerequisites)?

**Comment by chark1es** [comment]
Try to do the following: 

0. Install GO and Hugo **Extended** and NodeJS
1. Clone the repo
2. Open the terminal for that repo and run `npm run update-modules`
3. (Optional) Run the `npm run remove-darkmode` if you want to remove darkmode
4. Run `npm install`
5. Run `npm run project-setup`
6. Run `npm run dev`

Hopefully it works!

**Comment by Productivix** [comment]
hi, I had the same message, 
I typed `npm run update-modules`
then again `npm run dev` and it started correctly.
It is a complex theme...

**Comment by obreo** [comment]
I followed all the instructions as mentioned in the comments above and the prerequisites but I get the same error

**Comment by tfsomrat** [comment]
Hey @obreo,
first install all the prerequisites, and then follow the attached video instructions. it must work.
