### ISSUE TITLE
Quality of Life requests

### ISSUE THREAD

**Issue by chark1es** [zeon-studio/hugoplate#31]
I don't know if I am supposed to suggest QoL requests but I saw the enhancement tag so I assumed that's okay?

- In the readme file, I believe it would be better for the user to remove the dark mode before the `project setup` script is ran.
- There should be a button to copy any code
- The lines should be numbered 
- Add a PDF file viewer shortcode 
- Add a language slider if there are only two languages (similar to the dark/light theme switcher)
- Keep the language selector on all pages (as of right now, it only shows up on the homepage)
- Add a read time shortcode for the blog posts

**Comment by tfsomrat** [comment]
Hey @chark1es 

Thanks for your suggestions. As you know, it's an Open Source Starter template. so you can't expect to have everything on it. it's a kind of developer-focused template. developers can add their required functionality to it. it's just e jump start for them.

Also, I wanna mention that you are welcome to contribute to improving its functionality. thanks
