### ISSUE TITLE
Colors not updating from changes to theme.json 

### ISSUE THREAD

**Issue by dailyprice** [zeon-studio/hugoplate#33]
From the Readme (https://github.com/zeon-studio/hugoplate#-colors-and-fonts), it appears that changing the hex codes in the `theme.json` file should update the colour scheme of the website, however this does not happen. Stopping and re-running the server does not appear to implement the colour changes either.

Is there a separate command that I need to run in order for the changes to `theme.json` to be reflected?

**Comment by tfsomrat** [comment]
hi @dailyprice 
Thanks for your concern. It was a cache issue. I fixed it. please download the latest version, and remember that it requires hugo_extended v0.118.2 to run.
