### ISSUE TITLE
Social Media Links

### ISSUE THREAD

**Issue by PerpetualStudio** [zeon-studio/hugoplate#37]
The social media share links (buttons) appear to be broken on my end and on your demo site.

The problem seems to be located somewhere around line 10 of the social-share module.

`{{ $url := printf "%s" .Permalink | absLangURL }}`

The formatting seems to be okay according to the Go lang docs. https://pkg.go.dev/fmt

I'm not sure what's wrong but I'm sure its something simple I'm overlooking.

**Comment by tfsomrat** [comment]
Did you update the `baseURL` in the `hugo.toml` file?

**Comment by PerpetualStudio** [comment]
> 

Yes I did. You can see the problem exists on the demo site as well. If you look here [on the demo site](https://hugoplate.netlify.app/blog/post-2/)

Scroll down and hover over the share links and you will see they are all incorrect.

Here's an example of the Facebook share https://facebook.com/sharer/sharer.php?u=%25%21s%28%3cnil%3e%29 <<< this is all wrong.

**Comment by somratpro** [comment]
that's because demo site doesn't have any baseURL

**Comment by neural-loop** [comment]
I set baseURL and my links still show https://facebook.com/sharer/sharer.php?u=%25%21s%28%3cnil%3e%29 , not sure if it is due to being in development mode. they each have %!s(<nil>)

**Comment by tfsomrat** [comment]
Host it with netlify or something else, and check it. if the issue still presents, then share your repo with me.

**Comment by PerpetualStudio** [comment]
Correct me if I'm wrong, but I don't understand what the baseURL has to do with this. The [social share module](https://github.com/gethugothemes/hugo-modules/blob/master/components/social-share/layouts/partials/social-share.html) is using a formatted .Permalink value to generate the social media sharing link. I don't think that value is being derived from the baseURL or anything else set in the hugo configuration.

**Comment by tfsomrat** [comment]
Hey @neural-loop 

Sorry for the misunderstanding. we had an issue, and baseURL is also required when you live the site. anyway, I fixed the issue on our end. you just need to update the theme, and put a BaseURL when you are going to live it. thanks

**Comment by ElioDiNino** [comment]
@tfsomrat What is the best way to "update the theme" on an already initialized project?

**Comment by tfsomrat** [comment]
how did you connect the theme? as a module or as a theme in the themes folder?

**Comment by ElioDiNino** [comment]
> how did you connect the theme? as a module or as a theme in the themes folder?

I used GitHub's "Use this template" option and then ran the project setup script

**Comment by tfsomrat** [comment]
ok, then you need to download the theme and replace your `themes/hugoplate` folder. or simply update the `social-share` partial call in the `blog/single.html` with this
```
{{ partial "social-share" (dict "Context" . "Class" "share-icons" "Title" (i18n "share") "Whatsapp" false "Telegram" false) }}
```
and run `npm run update-modules`

**Comment by ElioDiNino** [comment]
> ok, then you need to download the theme and replace your `themes/hugoplate` folder. or simply update the `social-share` partial call in the `blog/single.html` with this
> 
> ```
> {{ partial "social-share" (dict "Context" . "Class" "share-icons" "Title" (i18n "share") "Whatsapp" false "Telegram" false) }}
> ```
> 
> and run `npm run update-modules`

In that case, would it be best (to keep up to date with changes) to instead just add the theme as a git submodule and just pull the changes?

**Comment by tfsomrat** [comment]
you can do that, or you can use the theme as hugo module.

**Comment by ElioDiNino** [comment]
> you can do that, or you can use the theme as hugo module.

If I do it as a Hugo module though, the code in the themes folder doesn't get updated, right?
