### ISSUE TITLE
Unable to remove darkmode

### ISSUE THREAD

**Issue by harisharjun** [zeon-studio/hugoplate#38]
While I am running `npm run remove-darkmode`  in the projects folder, I am getting this error:
```
node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'layouts'
    at Object.readdirSync (node:fs:1527:3)
    at removeDarkModeFromPages (/Users/kharisharjun/hugo/hugoplate/scripts/removeDarkmode.js:30:20)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/kharisharjun/hugo/hugoplate/scripts/removeDarkmode.js:16:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'layouts'
}

Node.js v18.17.1
```

Please help me how to proceed. Unable to find any suitable resolution.
I suspect it is something to do with my npm, but unable to resolve it...

**Comment by tfsomrat** [comment]
Please run this command before run `project-setup`. it must work. thanks

**Comment by harisharjun** [comment]
Didn't help. I am getting the same error even after `npm run project-setup`.

**Comment by tfsomrat** [comment]
I said before, not after

**Comment by harisharjun** [comment]
I meant I tried it before only. This is the order in which I tried.
```
npm run project-setup
npm run remove-darkmode
```

But even after trying this, I am getting the same error.

**Comment by tfsomrat** [comment]
I don't know man, I just tried it on my machine and other machines too. working perfectly. maybe your node version is not matching. try to install nodejs 18

**Comment by harisharjun** [comment]
I am on `node v18.17.1` But still getting the same error.

**Comment by tfsomrat** [comment]
In that case, you should remove `dark-mode` manually, it's not that hard. I checked the script on every platform `windows, linux, mac` and everywhere it works. I don't know what happened on your end. but I am pretty sure it's not the script issue. thanks

**Comment by stacygaudreau** [comment]
I ran into this as well.

Correct steps after a fresh `git clone` of the `hugoplate` repo to remove dark mode:

1. `cd <reponame`>
2. `npm install`
3. `npm run remove-darkmode`
4. `npm run project-setup`

If you forgot the `npm install` first, you will have issues.

**Comment by harisharjun** [comment]
I did try the npm install but didn't work.

So, I manually changed the settings in the config file directly to remove
the darkmode, and it worked!

Regards!
