### ISSUE TITLE
Authors image - using partial "image", but doesn't honor the "size" value set

### ISSUE THREAD

**Issue by neural-loop** [zeon-studio/hugoplate#39]
I copied the authors list.html and was working to refactor it for another list of content

`    {{ partial "image" (dict "Src" $image "Alt" .Title "Class" "mx-auto mb-6 rounded" "size" "120x120") }}
`
In the resource that is rendered, it is the same size as it was before. "size" seems to be completely ignored in the output. I've tried to find the image partial, but there isn't anything. I searched through hugo documentation to try to find out if it was a built in template and tried chatgpt but haven't been able to find anything. Any idea?

**Comment by tfsomrat** [comment]
Hey @neural-loop  thanks for your concern. it was a little typo mistake, the `size` should be `Size` with capital "S". I also fixed it in the author-single page.

**Comment by neural-loop** [comment]
Could you describe what the image partial is? I couldn't find documentation or an image.html, is it included somewhere in the config?

**Comment by tfsomrat** [comment]
here is the docs: https://github.com/gethugothemes/hugo-modules/tree/master/images#image-implementation
