### ISSUE TITLE
Do you have a showcase? I've released the site I have been working on using hugoplate

### ISSUE THREAD

**Issue by neural-loop** [zeon-studio/hugoplate#41]
https://aimodels.org/

I thought I saw a showcase somewhere, but I can't find it on the zeon-studio site so I'm uncertain. This issue can be closed. 

Thanks for the great theme. I'll still have to figure out some things with the title for the front page being in the config, which makes some tricky issues in the places where the 'site name' is used outside of front page title.

**Comment by tffarhad** [comment]
Hi @neural-loop,
Thank you for using Hugoplate. Statichunt has a showcase for static sites you can submit [there](https://statichunt.com/examples). The team will add it if it meets all criteria.

**Comment by neural-loop** [comment]
Here's another site I built using a customized hugoplate https://open-neuromorphic.org/

**Comment by tffarhad** [comment]
Hi @neural-loop, 
Thank you for using Hugoplate for your project.
We've added a showcase to the Hugoplate README file and featured your two projects, [check here](https://github.com/zeon-studio/hugoplate#%EF%B8%8F-showcase).
Please feel free to add any other projects you have.

Thank you.
