### ISSUE TITLE
Title issue on homepage

### ISSUE THREAD

**Issue by genvlad** [zeon-studio/hugoplate#44]
Hello, 
I would like to ask about title definition for the home page. I have your clean project from github, without my other changes.

I have /content/english/homepage/_index.md and I try to define title like in  /content/english/about/_index.md

`---
title: "My title"
---`

but it doesnt work. I found that title is defined in hugo.toml on line 5, and there ist still visible title defined in toml file.

But I would like to realize multilanguage support and I can't imagine how to do it with toml file.

I think it should work like on others page.

I also tried to add other parameters to front matter, but it works everywhere but not in homepage, I dont know why.

I would like to ask also one thing what I don't fully understand. Where is configure that /content/english/homepage/_index.md will be homepage mapped to /. I search all config files and I dont't know understand how It is achieved.

Thank you for this theme and soon reply.

**Comment by genvlad** [comment]
The same issue is with description, keywords and so on.

**Comment by genvlad** [comment]
I rmoved homepage directory and moved _index.md to root of /content/english. Than I needed to change /theme/layouts/index.html file and everything works without problem.

**Comment by vnpnlz** [comment]
Same issue. I cannot change the `title` of the website and the `logo`.

**Comment by genvlad** [comment]
> Same issue. I cannot change the `title` of the website and the `logo`.

My solution was that I move /content/english/homepage/_index.md to root od folder english so /content/english/_index.md and remove "homepage mark" from layout page index.html and everything works fine.

**Comment by tfsomrat** [comment]
hey @genvlad, this is the only solution. so I moved it properly. you can update the theme to get the latest code. thanks
