### ISSUE TITLE
Menu Creation automatically?

### ISSUE THREAD

**Issue by romeocontrol** [zeon-studio/hugoplate#48]

**Comment by romeocontrol** [comment]
I want to create a site about a sonnenhaus, i.e. a house using sun energy an nothing else.
hugoplate is very nice to look at and modern. 
Is it correct: I have to create all menu entries in menus.de.toml 
or
ist there an automatic creation?
Thank you
RT

**Comment by tfsomrat** [comment]
hey @romeocontrol, I didn't get it.

**Comment by romeocontrol** [comment]
Good morning,
thanks for the quick reply!
I like Hugoplate very much, the design is modern. And it fits well with my project.
I installed it according to instructions and want to create my own page tree.
However, the newly created pages /.md documents or folders are not included in the menu.
My question:
Do I have to create each menu item including the subitems individually in the corresponding config file?
Or is there an automatic solution for this that I am overlooking.
Looking forward to feedback!
RT

Guten Morgen,
danke für die schnelle Antwort!
Hugoplate gefällt mir sehr gut, das Design ist modern. Und das passt gut zu meinem Projekt.
Ich habe es nach Anleitung installiert und möchte meinen eigenen Seitenbaum erzeugen.
Allerdings werden die neu erstellten Seiten /.md-Dokumente nicht im Menu berücksichtigt.
Meine Frage:
Muss ich jeden Menüpunkt inkl. der Unterpunkte einzeln in der entsprechenden config-Datei erstellen?
Oder gibt es dafür eine automatische Lösung, die ich übersehe.
Freue mich auf Rückmeldung!
RT

**Comment by tfsomrat** [comment]
you need to add menu items in the `config/_default/menus.*.toml` file. thanks
