### ISSUE TITLE
Great hugo theme created with tailwind css

### ISSUE THREAD

**Issue by wtsang11** [zeon-studio/hugoplate#51]
But, can you write an eBook to teach the nuts and bolts in developing the theme?  This will be a good reference for new hugo developers.  I will definitely buy a copy if you wrote it.

**Comment by tfsomrat** [comment]
hey @wtsang11 
thanks for your interest, there is a doc for a theme that has a similar approach to build it, you can try it https://docs.gethugothemes.com/spydea/installation/
