### ISSUE TITLE
how to add google analytics

### ISSUE THREAD

**Issue by whereissam** [zeon-studio/hugoplate#52]
I saw the doc include tag manager & adsense but not include google analytics. I follow the variable name google_analytics than follow the guide in web but I can't set correctly.  Below is my code

head.html
```
<!-- google analytics -->
{{ if not .Site.IsServer }}
{{ template "_internal/google_analytics_async.html" . }}
{{ end }}
```

layouts/_internal/google_analytics_async.html
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-');
</script>
```

config/_default/params.toml
```
googleAnalytics = "G-"
```

Do anybody know how to set GA? please help me.

**Comment by tfsomrat** [comment]
hey @whereissam, you are using internal template, so don't add it manually in the layout again. remove this file `layouts/_internal/google_analytics_async.html`.

and then if you want to use GA4, then add `{{ template "_internal/google_analytics" . }}`. and set the code into `hugo.toml`

for more info, check the original doc https://gohugo.io/templates/internal/#configure-google-analytics

**Comment by whereissam** [comment]
Thanks for reply, I follow [Add Minimal Analytics (Google Analytics v4) to Hugo](https://discourse.gohugo.io/t/add-minimal-analytics-google-analytics-v4-to-hugo/39016) this instruction to successfully add GA.!
