### ISSUE TITLE
ERROR POSTCSS - can't run dev

### ISSUE THREAD

**Issue by GroupeLudix** [zeon-studio/hugoplate#53]
Hi !

Got that error when using `npm run dev` :

`ERROR POSTCSS: failed to transform "css/style-lazy.css" (text/css): 'C:\Program' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
Built in 1482 ms
Error: error building site: POSTCSS: failed to transform "css/style.css" (text/css): 'C:\Program' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.`

Hugo version : hugo v0.119.0-b84644c008e0dc2c4b67bd69cccf87a41a03937e+extended windows/amd64 BuildDate=2023-09-24T15:20:17Z VendorInfo=gohugoio
Node version :  Node.js v20.9.0
Go version : go version go1.21.3 windows/amd64

**Comment by tfsomrat** [comment]
please follow the instructions https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#-getting-started
