### ISSUE TITLE
you tube: bug: scrolls away on click

### ISSUE THREAD

**Issue by gedw99** [zeon-studio/hugoplate#55]
on safari Mac when you start the video there the page scrolls away from the video

https://github.com/gethugothemes/hugo-modules/tree/master/videos#youtube-video-lite-and-fast

**Comment by tfsomrat** [comment]
hello @gedw99, this is not actually the YouTube issue, it's actually happening for the image slider, because all the slider image heights are not the same.  If you remove the slider or choose the same height image, the issue should be resolved. thanks
