### ISSUE TITLE
Dependencies at build time

### ISSUE THREAD

**Issue by gedw99** [zeon-studio/hugoplate#57]
Let’s add a make file to setup all dependencies 

then calls to package.json will work first time

**Comment by gedw99** [comment]
Dev container does the same thing.

So coukd just have the makefile call into that too so devs can either run with or without docker.

**Comment by tfsomrat** [comment]
Hey @gedw99, I didn't understand it properly. can you please elaborate, or you can create PR to contribute to the projects. thanks

**Comment by gedw99** [comment]
Will do a PR... you can see if its useful or not
