### ISSUE TITLE
projectSetup.js

### ISSUE THREAD

**Issue by gedw99** [zeon-studio/hugoplate#58]
It takes the ExampleSite folder and moves all the folders and their files up to root.
I think it's designed so you can bootstrap into root different project defaults ?

If I have to run it in order to work on the code, then how can I do a PR ? 
Is there a way to run it locally without destroying the folder structure ?

**Comment by gedw99** [comment]
I think I worked it out

```makefile


EX_CMD=cd $(REPO_FSPATH)/exampleSite &&
ex-init:
	# This does not collapse the folders
	$(EX_CMD) npm install
ex-build:
	$(EX_CMD) npm run build:example
	# pumps out to public, for static deploy.
ex-preview:
	$(EX_CMD) npm run preview:example
	# http://localhost:1313
```

Anything I missed ?

**Comment by tfsomrat** [comment]
Hey @gedw99, `project-setup` is compulsory if you want to customize the theme. If you don't run `project-setup` it will load everything using hugo modules. and no layout changes will be affected. thanks

**Comment by gedw99** [comment]
yep thanks - suggest adding something about this to README, as its needed to work on this
