### ISSUE TITLE
failed to download modules: binary with name "go" not found

### ISSUE THREAD

**Issue by Sakh1l** [zeon-studio/hugoplate#59]
when i try to run the command npm run update-modules am getting below error in linux.

> hugoplate@1.9.3 update-modules
> node ./scripts/clearModules.js && hugo mod clean --all && hugo mod get -u ./... && hugo mod tidy

File does not exist.
Error: failed to load modules: failed to download modules: binary with name "go" not found

I understand that it has an issue with go modules file go.mod. The same error comes up when we run "hugo mod get -u"

**Comment by arthurzinck** [comment]
Hi @Sakh1l, have you golang installed ?

**Comment by Sakh1l** [comment]
Hi, yes. I have all three node, Hugo extended and go as said/above versions
installed

**Comment by tfsomrat** [comment]
Hey @Sakh1l, you may need to export `go` path. this [thread](https://stackoverflow.com/questions/21001387/how-do-i-set-the-gopath-environment-variable-on-ubuntu-what-file-must-i-edit) could help you. or you can more specific with your OS and search google how to export go path on `windows/mac/linux`. 

If everything goes well, then you can see the go version on the terminal by typing `go version`. thanks

**Comment by Sakh1l** [comment]
@tfsomrat Hi, no. I tried that as well. Go path is exported and I have it in my shell environment.

**Comment by tfsomrat** [comment]
please run `go version`, `hugo version` and `node -v` in the terminal, and give me the output here.

**Comment by Sakh1l** [comment]
Here is the output. Thanks @tfsomrat 

go version
go version go1.20.5 linux/amd64

hugo version
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended linux/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio

node -v
v18.17.1

![Screenshot from 2023-11-25 18-42-47](https://github.com/zeon-studio/hugoplate/assets/59551125/bdf16b00-71bf-491e-aff9-5562a40fb024)

**Comment by Sakh1l** [comment]
Thanks @tfsomrat . I have installed the golang from apt repo and it worked fine. Earlier, complied it from the source code.
Now, it works. Thanks for your time and effort on looking in it.
