### ISSUE TITLE
Accessibility tests

### ISSUE THREAD

**Issue by dryscord** [zeon-studio/hugoplate#6]
See https://wave.webaim.org/report#/https://hugoplate.netlify.app/ (I'd suggest you install their extension and test every page of the theme thoroughly in both light and dark modes)

**Comment by mehedi-sharif** [comment]
Thank you for you findings @dryscord . We are going to fix this issue soon.

**Comment by tfsomrat** [comment]
Hi @dryscord 

I have fixed the errors. now some alerts are still showing. Since it's a starter template, the alerts will go out when developers will build a site on it.  Let me know what you think.
