### ISSUE TITLE
Issues with GitHub Actions deployment

### ISSUE THREAD

**Issue by valentinneher** [zeon-studio/hugoplate#60]
Hi Everyone!

Not sure if this is the right place to ask as I'm a newbie. Basically I cloned the template, just did minor text changes on the main page and it runs perfectly locally but does not deploy properly with the provided gh action.

Followed the steps here: https://gohugo.io/hosting-and-deployment/hosting-on-github/
The action runs successfully but the deployed page does not look as it should.

Link to the project: https://github.com/high-five-app/website/actions/runs/6991485038

Do you have any suggestions as to what I could be doing wrong?

Thank you very much!

**Comment by tfsomrat** [comment]
Hey @valentinneher, Thanks for choosing Hugoplate. You just need to set this `https://high-five-app.github.io/website/` as your `baseURL` in the `hugo.toml` file. and you are good to go. have a nice day.

**Comment by valentinneher** [comment]
Thank you so much! @tfsomrat 
I think it might be helpful for other users to elaborate a bit more on that or provide a little example in the README.md.
Have a great day! 🔥
