### ISSUE TITLE
No styles when using custom domain on github.

### ISSUE THREAD

**Issue by RoboticsIOEPC** [zeon-studio/hugoplate#63]
https://robotics.ioepc.edu.np

when using this address in github pages and also in hugo.toml it doesn't show any styles in the site whereas if I did't use a custom address and used the default github.io address it works flawlessly.

baseURL = "https://robotics.ioepc.edu.np"
is set too

**Comment by RoboticsIOEPC** [comment]
Last thing I added was a trailing slash after my address in hugo.toml 

baseURL = "https://robotics.ioepc.edu np/"

and I slept. Wow it's really working, I'll be keeping the issue open for a day, see if changes on the site breaks it again.

**Comment by scientiac** [comment]
In the last line of `/themes/hugoplate/layouts/partials/essentials/style.html`

I replaced `href="{{ $styles.RelPermalink }}"` with `href="{{ $styles.Permalink }}"` and it fixed the issue.
