### ISSUE TITLE
How to use contact form?

### ISSUE THREAD

**Issue by danijeljw-RPC** [zeon-studio/hugoplate#64]
Is there a way to use the contact form? I looked at the content, and it just has the following:

```md
---
title: "Contact"
meta_title: ""
description: "this is meta description"
draft: false
---
```

When I try to use that, it takes me a 404, which I expected, but I cannot see how to configure this? Can I add something that allows the page to actually submit the request?

**Comment by tfsomrat** [comment]
hey @danijeljw-RPC, please see the doc from here, we use same approach https://docs.gethugothemes.com/guide/#contact-and-subscription-form
