### ISSUE TITLE
Accessing Hugo Modules js files

### ISSUE THREAD

**Issue by 4ltrem** [zeon-studio/hugoplate#65]
Hello I'm trying to access modal.js but it isn't included in the project, when I run the server I can see the component and use it but because of how my site is structured I need to modify the js file but I cannot find it.

I appreciate any help I can get

-A

**Comment by tfsomrat** [comment]
Hey @4ltrem, you can't access the modules file in your theme. if you want to modify, then you need to create this file on your own. here is the modal js file, if it helps https://github.com/gethugothemes/hugo-modules/blob/master/modal/assets/js/modal.js
