### ISSUE TITLE
Problems with hasChildren in multiple languages

### ISSUE THREAD

**Issue by Mxucc** [zeon-studio/hugoplate#66]
Just like on the picture, when another language is used as the menu of hasChildren, there will be a menu that cannot be displayed.
![image](https://github.com/zeon-studio/hugoplate/assets/128977511/47025ab4-1aa5-45c2-b8cd-e67d2fafa257)
![image](https://github.com/zeon-studio/hugoplate/assets/128977511/1757028f-793b-4edb-add1-a2eae0fb1f96)
Refer to the multi-language Hugo configuration modification on the Internet but it still doesn’t work.
![image](https://github.com/zeon-studio/hugoplate/assets/128977511/faaabbb9-6dfb-4b3b-a5c2-9ee7e8926129)

**Comment by tfsomrat** [comment]
did you add this to the `languages.toml` file?
```
[Zh_CN]
languageName = "Zh_CN"
languageCode = "Zh_CN"
contentDir = "content/zh_cn"
weight = 2
```

**Comment by Mxucc** [comment]
> did you add this to the `languages.toml` file?
> 
> ```
> [Zh_CN]
> languageName = "Zh_CN"
> languageCode = "Zh_CN"
> contentDir = "content/zh_cn"
> weight = 2
> ```
This file was modified from the beginning
![image](https://github.com/zeon-studio/hugoplate/assets/128977511/b1365633-6746-4c43-896e-a18e38980038)
Yesterday I changed all Zh_CN to zh_CN. It is a matter of personal habits, but this does not solve this problem.
I think all my configurations are normal

**Comment by Mxucc** [comment]
> did you add this to the `languages.toml` file?
> 
> ```
> [Zh_CN]
> languageName = "Zh_CN"
> languageCode = "Zh_CN"
> contentDir = "content/zh_cn"
> weight = 2
> ```

I think you are right, there is a problem with capitalization
