### ISSUE TITLE
Dark mode has h1, h2, h3 and h4 displayed in blue in class content

### ISSUE THREAD

**Issue by thierry-tct** [zeon-studio/hugoplate#67]
In Dark mode, on the page `/elements/`, the sections titles are displayed in blue, instead of white.

**Comment by tfsomrat** [comment]
please add a screenshot

**Comment by thierry-tct** [comment]
I did the following:
1. Download the repo as zip and extract
2. cd into the extracted folder
3. run `npm run project-setup`
4. run: `npm install`
5. run: ` npm run dev`
6. Open the following link on web browser (Chrome or Edge): `http://localhost:1313/blog/post-2/`

The page display is the one in the screenshot.
![Capture-hugoplate](https://github.com/zeon-studio/hugoplate/assets/5491281/0f325433-0014-4c74-bbc0-fb393ad42be5)

**Comment by tfsomrat** [comment]
Hey @thierry-tct, I was trying to figure out the cause behind the issue. but I really couldn't find it. It works perfectly on every machine. could you try to deploy it on netlify or vercel to see that the issue is still happen or not?

**Comment by thierry-tct** [comment]
Thank you for your response @tfsomrat .

I made a fork of the current main branch (https://github.com/thierry-tct/hugoplate) and deployed on netlify at the following link https://main--curious-pony-25bd09.netlify.app/elements/

The issue also appears there.

**Comment by tfsomrat** [comment]
hey @thierry-tct, thanks for giving me this URL. I found out the issue and fixed it. please re-download the theme and enjoy.

**Comment by thierry-tct** [comment]
Hello @tfsomrat , Thank you for the fix. I tried, it works fine now.
Have a blessed end of the year.
