### ISSUE TITLE
Installation procedure is obscure - clarify how to update the theme

### ISSUE THREAD

**Issue by publicimageltd** [zeon-studio/hugoplate#68]
I'm not a web developer, but I did already install hugo pages. So the installation procedure, as it is described in the readme, remains obscure to me. First of all: Why do I have to clone the the repository in a separate dir and not simply in the themes folder? And most importantly: How can I update the theme? The readme asks me  to run commands like `npm run project-setup`, so would I need to repeat this procedure again? It all seems hacky and unclear. Furthermore, the doc talks about "updating modules", but what does that mean? GO modules, or theme-internal modules? 

Here's an example of an installation instruction which is more understandable: [PaperMode](https://github.com/adityatelange/hugo-PaperMod/wiki/Installation)

So in consequence, I'm shying away from using and customizing this template. I don't really know what to do (does the script folder from the cloned repo, for example,  belong into the hugo root folder?), and I don't know if all the effort is worth it, because I do not know how to seamlessly update. The theme looks really nice, but I won't touch it for now.

**Comment by tfsomrat** [comment]
Hey @publicimageltd, thanks for choosing Hugoplate. we made Hugoplate so that a developer can jumpstart a Hugo project. so we create some scripts to do it. but this template does not require extra effort to maintain. you can use it like any other Hugo theme. you can simply put it in the Themes folder and it will work. To update it later, you can redownload the theme and replace it in your Themes folder. Give it a try. Thanks

**Comment by publicimageltd** [comment]
Thanks! Another thing that confused me that the instructions recommend using `npm` even to serve the website locally, for which I would usually call `hugo server`. I'll give i t a try in the standard way, then. I understand now that this also is for the developer. 

Your instructions could benefit from simply explicitly addressing the two target audiences, e.g. in saying: "For Developers:" ..., and "For users of the theme".

**Comment by publicimageltd** [comment]
Just copying the cloned repo into the `themes` folder yields:

```
execute of template failed: template: partials/essentials/head.html:12:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: partial "favicon" not found
```

I guess I have to copy some stuff from the examplesite?

**Comment by tfsomrat** [comment]
try to run `go mod init example.com` in the terminal first. because we use Hugo modules to serve many components and functionality.

**Comment by gedw99** [comment]
I made a makefile to help with all this.

Let me know if you want it.

**Comment by tfsomrat** [comment]
please show me

**Comment by gedw99** [comment]
hey @tfsomrat 

This is a bit of a monster that does everything. 

If you want I can clean this up an PR it. Then we can work out the subtle changes needed.

```sh
make ex-build
``` 


```make
MK=$(GIO_MAKE_FSPATH)

include $(MK)/os.mk
OS_BIN_POLICY=global

include $(MK)/caddy.mk
include $(MK)/fly.mk
include $(MK)/hugo.mk
include $(MK)/minio.mk

print:
	@echo "GIO_MAKE_FSPATH:      $(GIO_MAKE_FSPATH)"

	$(MAKE) hugo-print
	$(MAKE) fly-print



REPO_NAME=hugoplate
REPO_FSPATH=$(PWD)/$(REPO_NAME)


dep:
	git clone https://github.com/zeon-studio/hugoplate
	@echo $(REPO_NAME) >> .gitingore
dep-del:
	rm -rf $(REPO_NAME)

dep-tools:
	$(MAKE) hugo-dep
	$(MAKE) fly-dep



EX_FSPATH=$(REPO_FSPATH)/exampleSite
EX_CMD=cd $(EX_FSPATH) &&
ex-init:
	# This does not collapse the folders
	$(EX_CMD) npm install
ex-build:
	$(EX_CMD) npm run build:example
	# pumps out to public, for static deploy.
ex-preview:
	$(EX_CMD) npm run preview:example
	# http://localhost:1313

ex-caddy:
	$(MAKE) caddy-server-run
	# https://localhost
	# https://browse.localhost
	# https://hello.localhost
	# https://example.localhost


REPO_CMD=cd $(REPO_FSPATH) &&
HUGO_SRC_FSPATH=$(REPO_FSPATH)

collapse:
	# This collapses the folders !!! DONT 
	# From https://github.com/zeon-studio/hugoplate/blob/main/.github/workflows/main.yml
	# It takes the ExampleSite folder and moves all the folders and their files up to root.
	# I think its designed so you can bootstrap into root differnet project defaults ?
	# The problem i have is that i cant do a PR then !!!
	#$(REPO_CMD) npm run project-setup
	# standard
	$(REPO_CMD) npm install

mod-updates:
	# updates hugo modules
	$(REPO_CMD) npm run update-modules
run:
	$(MAKE) hugo-ops-dev
build:
	$(MAKE) hugo-ops-build
serve:
	$(MAKE) hugo-ops-serve
	# http://localhost:1313

FLY_SRC_APP=gedw99-hugoplate
FLY_SRC_FSPATH=$(REPO_FSPATH)

deploy:
	# need to make a docker and fly confif first
	# can just embed hugo for now and run it as hugo serve on port 1313.
	$(MAKE) fly-deploy

```

**Comment by alienievecado** [comment]
> I'm not a web developer, but I did already install hugo pages. So the installation procedure, as it is described in the readme, remains obscure to me. First of all: Why do I have to clone the the repository in a separate dir and not simply in the themes folder? And most importantly: How can I update the theme? The readme asks me to run commands like `npm run project-setup`, so would I need to repeat this procedure again? It all seems hacky and unclear. Furthermore, the doc talks about "updating modules", but what does that mean? GO modules, or theme-internal modules?
> 
> Here's an example of an installation instruction which is more understandable: [PaperMode](https://github.com/adityatelange/hugo-PaperMod/wiki/Installation)
> 
> So in consequence, I'm shying away from using and customizing this template. I don't really know what to do (does the script folder from the cloned repo, for example, belong into the hugo root folder?), and I don't know if all the effort is worth it, because I do not know how to seamlessly update. The theme looks really nice, but I won't touch it for now.

I think the instructions on how installed this theme are very clear, in order to update the theme I recommended use `git fetch`

**Comment by jmMeessen** [comment]
I need to confess that I am lost too.

My current version, from `package.json`, is 1.7.7 and I see that the current version is 1.10.3. I want to upgrade to the latest to fix some solved issues.

I tried to run `npm run update-modules` but apparently it failed with the error message 
```
hugo: downloading modules …
hugo: collected modules in 4534 ms
go: downloading github.com/gethugothemes/hugo-modules v0.0.0-20231227015948-b2308653c9e2
go: downloading github.com/gethugothemes/hugo-modules/shortcodes v0.0.0-20231227015948-b2308653c9e2
go: malformed module path "hugoplate": missing dot in first path element
```

I fear that `git fetch` will not work. I might not have installed the way it is supposed. This is how I proceeded:
- I cloned the template directory with `gh repo clone zeon-studio/hugoplate`
- Setup the project with `npm run project-setup` and start customising it for my needs
- renamed the directory, stripped the .git directory so that I could create a new project  on GitHub to store and version it

Where did I go wrong ? 
What should I do?

**Comment by tfsomrat** [comment]
hey @jmMeessen, could you try `npm run theme-setup` and then `npm run update-modules`, and then run `npm run project-setup` again? let me know what happens.

**Comment by jmMeessen** [comment]
Hi @tfsomrat 

I ran the recommended steps and didn't see anything weird. See hereafter the log files so that you can validate my assumption. 

```
git:(13-move-old-blog-posts) ✗ npm run theme-setup

> hugoplate@1.7.7 theme-setup
> node ./scripts/themeSetup.js
```

```
git:(13-move-old-blog-posts) ✗ npm run update-modules

> hugoplate@1.7.7 update-modules
> node ./scripts/clearModules.js && hugo mod clean --all && hugo mod get -u ./... && hugo mod tidy

File does not exist.
Deleted 449 files from module cache.Update module in /Users/jmm/work/the-captains-shack/exampleSite
go: no module dependencies to download
go: downloading github.com/zeon-studio/hugoplate v0.0.0-20240101043423-aa00fbb34355
hugo: downloading modules …
go: added github.com/zeon-studio/hugoplate v0.0.0-20240101043423-aa00fbb34355
go: downloading github.com/gethugothemes/hugo-modules v0.0.0-20231227015948-b2308653c9e2
go: downloading github.com/gethugothemes/hugo-modules/search v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/search v0.0.0-20231227015948-b2308653c9e2

(...)

go: downloading github.com/gethugothemes/hugo-modules/seo-tools/basic-seo v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/seo-tools/basic-seo v0.0.0-20231227015948-b2308653c9e2
go: downloading github.com/gethugothemes/hugo-modules/seo-tools/site-verifications v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/seo-tools/site-verifications v0.0.0-20231227015948-b2308653c9e2
go: downloading github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager v0.0.0-20231227015948-b2308653c9e2
hugo: collected modules in 19621 ms
➜  the-captains-shack git:(13-move-old-blog-posts) ✗
```

```
➜  the-captains-shack git:(13-move-old-blog-posts) ✗ npm run project-setup

> hugoplate@1.7.7 project-setup
> node ./scripts/projectSetup.js

➜  the-captains-shack git:(13-move-old-blog-posts) ✗
```

I didn't see any changes on the file system appart from changes to the go.mod file.

I then re-ran the `npm run update-modules` and get the same result as can be seen hereafter:
```
(...)
go: added github.com/gethugothemes/hugo-modules/shortcodes/button v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/shortcodes/notice v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/seo-tools/basic-seo v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/seo-tools/site-verifications v0.0.0-20231227015948-b2308653c9e2
go: added github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager v0.0.0-20231227015948-b2308653c9e2
hugo: collected modules in 13981 ms
Deleted 485 files from module cache.Update module in /Users/jmm/work/the-captains-shack
hugo: downloading modules …
hugo: collected modules in 4788 ms
go: downloading github.com/gethugothemes/hugo-modules v0.0.0-20231227015948-b2308653c9e2
go: downloading github.com/gethugothemes/hugo-modules/shortcodes v0.0.0-20231227015948-b2308653c9e2
go: malformed module path "hugoplate": missing dot in first path element
➜  the-captains-shack git:(13-move-old-blog-posts) ✗
```

There seems to be no upgrade when I checked in the `package.json` and the bug I want to get rid of (inline code being black in dark mode)  is still there.

My setup can be seen at https://github.com/jmMeessen/the-captains-shack/tree/13-move-old-blog-posts?tab=readme-ov-file

If we run out of ideas, I can start the initial procedure that I described earlier all over again and try to move my pages, config, and github action by hand. It might be a bug in the version I started with that prevents the `update-module` to work properly.

**Comment by publicimageltd** [comment]
Thanks for all your posts. 

Judging from the Makefile posted and the discussion so far, I conclude that installing hugoplate requires more than just cloning the repo into the theme folder. Just calling `git fetch` in that folder did, of course, change nothing, since I had a fresh clone installed. I'll not dwell on that, but the instructions are ambivalent; I can point out some examples if wanted. I think, however, that it is more productive to help improving the instructions, so I'd post a PR once I got the website running.

I think my confusion partly stems from the different 'root folders' available. I did `npm run project-setup` and `npm run update-modules` right from within the subdirectory 'themes/hugoplate'. A lot of stuff has been downloaded, but `hugo serve` then complains that PostCSS is missing. I then switched to the the root directory of my freshly set up hugo root directory, but there, however, these scripts are not available. 

So could you, please, specify the exact steps to install a fresh, running, blank website **without the examplesite** from scratch?

**Comment by tfsomrat** [comment]
hey @publicimageltd please follow the video step by step https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#-still-confused-watch-a-quick-video

it's the easiest way to install a fresh project. it will also remove the exampleSite.

**Comment by publicimageltd** [comment]
Thanks, but I won't use this theme now anyways. I have opted for a more documented theme.

**Comment by tfsomrat** [comment]
Hey @jmMeessen, I have added a new script for updating the theme. please check https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#-update-theme
