### ISSUE TITLE
Help using CSS

### ISSUE THREAD

**Issue by gliese3** [zeon-studio/hugoplate#69]
Hi! First, thank you very much for allowing using this theme for free! But I have a somewhat stupid question.

Haven't found information about how CSS files are actually generated. For example, I would like to change image size for **"blog-card.html"** partial, but do not understand where original CSS files are placed. I was able to find them only after compiling in ```/resources/_gen/assets/css/css/```. Can you please help me with it?

Thank you!

P.S. I am really sorry if it is a wrong place to ask such kind of questions.

**Comment by tfsomrat** [comment]
hey @gliese3, you can find every CSS files in `assets/scss`. But I suggest you use the `custom.scss` file to write your CSS. thanks

**Comment by gliese3** [comment]
Yes, got it. Haven't heard about _scss_ before. Thank you!

**Comment by steam3d** [comment]
Any instruction? I added assets/scss/custom.scss, and it still does not work

**Comment by eqslab** [comment]
It worked perfectly for me. It is now possible to modify already existed styles from here or to add new ones. Don't know why it didn't work out for you.
