### ISSUE TITLE
Cookie consent not showing

### ISSUE THREAD

**Issue by scholtalbers** [zeon-studio/hugoplate#75]
I hit the same error as mentioned here https://github.com/gethugothemes/hugo-modules/issues/33
Adding the shown script to `themes/hugoplate/layouts/partials/essentials/script.html` fixed it.

**Comment by tfsomrat** [comment]
hey @scholtalbers, the issue has been fixed. you just need to make the `lazy=false` in your `hugo.toml` file. 

```
[[params.plugins.js]]
link = "plugins/cookie.js"
lazy = false
```

don't add any extra script. thanks
