### ISSUE TITLE
Update-theme fails

### ISSUE THREAD

**Issue by jmMeessen** [zeon-studio/hugoplate#77]
The `mpm run update-theme` described in the readme fails with `Missing script: "update-theme"`.

I proposed a fix with PR #76

**Comment by jmMeessen** [comment]
FYI
I tried the new command (after fixing the package.json).  It successfully completed. But running `npm run dev` immediately after failed with several page generation errors (sorry will need to run it again to capture the exact error messages).

But I fear that my inability to perform a complete `npm run update-modules` might be the cause for that.  So I didn't investigate further and rather concentrated on the update-modules issue.

My theme update experiment can be seen on this branch https://github.com/jmMeessen/the-captains-shack/tree/upgrade_theme

**Comment by tfsomrat** [comment]
Hey @jmMeessen, I accepted your PR, and `update-theme` doesn't break anything.
