### ISSUE TITLE
Blank Space after Link in Markdown

### ISSUE THREAD

**Issue by albertoreineri** [zeon-studio/hugoplate#78]
I have noticed that if a link ends with a period (.) or a comma (,) then a white space is added between the link and the period or comma. This also happens in the demo on the website (https://hugoplate.netlify.app/elements/) in the 'Link' section on the point "Or leave it empty and use the link text itself." The period at the end is preceded by a space."
I made a Google search and the problem could be related to trailing newlines issue, but I haven't found the link rendering template in the theme to try to solve it...

Many thanks for your work.

**Comment by tfsomrat** [comment]
Hey @albertoreineri, yes I can see the problem. but it's happening because of the `render-link` module. render-link provides some extra functionality to manipulate links in MD files. so if the space between the link and period bothering you, you can simply remove that module. thanks

**Comment by albertoreineri** [comment]
Hi @tfsomrat! Thank you so much for your quick answer! 
As I can read in Hugo Docs the render-link module should live in `layouts/_default/_markup/render-link.html` but I can't find it in Hugoplate theme, neither I can find a `render-link.html` file in all Hugo project... I tried to create `layouts/_default/_markup/render-link.html` in hugoplate theme folder in order to change the rendering of link but it didn't worked... May there be another way to maniputale the render-link?
Thanks!

**Comment by tfsomrat** [comment]
you will find it in the `modules.toml` file. you just need to remove that module

**Comment by albertoreineri** [comment]
@tfsomrat Thanks a lot, it works perfectly! Congratulations on this project and have a good day!
