### ISSUE TITLE
fallback-language for not-(yet)-translated pages

### ISSUE THREAD

**Issue by hanlectin** [zeon-studio/hugoplate#80]
is it possible to somehow specify a (defalut) fallback language - so that if e.g. I did not (yet) translate 
\content\en\somepage.md 
   to 
\content\en\somepage.de.md

"somepage.md" is rendered if the user selects "Deutsch" in the "language-switcher"

this is my languages.toml:
```
################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 1

################ German language ##################
[de]
languageName = "Deutsch"
languageCode = "de-at"
contentDir = "content/de"
fallback = ["en"]
weight = 1
```
...thanks!

**Comment by flexxgaad** [comment]
You can wrap the code switcher in an `if` so it only shows when a page has a translation.
```
{{- if .IsTranslated -}}
<!-- your language switcher code here -->
{{- end }}
