### ISSUE TITLE
npm run dev not working

### ISSUE THREAD

**Issue by heberleh** [zeon-studio/hugoplate#81]
> Use "hugo server [command] --help" for more information about a command.
> 
> Error: command error: Unable to locate config file or config directory. Perhaps you need to create a new site.
> Run `hugo help new` for details.

I installed Go, Nodejs, and Hugo ext, but I can't get it running:

- go version go1.21.6 linux/amd64
- nodejs v20.11.0

Project setup and npm install worked. The next command in the README is npm run dev, but that doesn't work.

Update: I tried to run it as dev container in VSCode
but it gave this erro:

> Error: command error: failed to load modules: module "hugoplate" not found in "/workspaces/hugoplate/exampleSite/themes/hugoplate"; either add it as a Hugo Module or store it in "/workspaces/hugoplate/exampleSite/themes".: module does not exist
> [164476 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.

Other stuff I tried
- which go: /usr/local/go/bin/go
- export GOROOT=/usr/local/go
- export GOPATH=$HOME/go
- export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

```
npm run update-modules

> hugoplate@1.11.1 update-modules
> node ./scripts/clearModules.js && hugo mod clean --all && hugo mod get -u ./... && hugo mod tidy

File does not exist.
Deleted 0 files from module cache.Update module in /home/h/github/hugoplate/exampleSite
go: cannot find GOROOT directory: /usr/local/go```

**Comment by heberleh** [comment]
Updating the Dockfile to use other urls and ubuntu+ node, and root as user in the json, and download go, node and hugo ext in the exact versions mentioned in the readme (not latest) seems to work as dev container.

**Comment by tfsomrat** [comment]
Hey @heberleh, I think your project-setup does not worked, that's why it's not running.
