### ISSUE TITLE
Warning : found no layout file for "HTML" for kind [...]

### ISSUE THREAD

**Issue by engboris** [zeon-studio/hugoplate#82]
Hello. I tried to follow the procedure to test the example website but I get the following warning `npm run dev`:

> WARN 2024/01/22 11:19:53 found no layout file for "HTML" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

Which other warnings for "home", "taxonomy", "section" and "term" instead of "page". The result is that nothing is rendered on `http://localhost:1313/` (blank page).  I also checked the video for the installation procedure.

Versions:
```
$ hugo version
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1

$ go version
go version go1.21.6 linux/amd64

$ node --version
v20.11.0
```

**Comment by tfsomrat** [comment]
hey @engboris, you need at least Hugo_Extended v0.115.1 to run this project. please follow the guide from here https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#-getting-started

**Comment by engboris** [comment]
Thank you. I misread the version number and mistook v0.92.2 for being more recent than v0.1[...].
