### ISSUE TITLE
Installation in existing Hugo project

### ISSUE THREAD

**Issue by vinRosso** [zeon-studio/hugoplate#83]
I've got a Hugo project in which I want to use this theme. [WIN 11]

For all the themes I've encountered until now it worked like this:
1. Submodule theme in Hugo project
```shell
cd path/to/hugo/project
git submodule add https://github.com/zeon-studio/hugoplate.git themes/hugoplate
```
2. Change the content of `hugo.toml` so that
```toml
theme = 'hugoplate'
```
3. Enjoy
```shell
hugo server
```
But doing this is giving me this error: `error calling partialCached: partial "favicon" not found`
I checked other issues but I couldn't find clear solutions:
`npm install` from #1 gives this error: `npm ERR! enoent ENOENT: no such file or directory, open 'path/to/hugo/project/package.json'`
`npm run update-modules` from #29 gives the same error as above
`go mod init example.com` from #68 doesn't work either :(

I'm not really a developer so if anyone could help me I would be glad.

**Comment by tfsomrat** [comment]
Hey @vinRosso, Sorry to hear that. I want to let you know that this theme has some dependencies that needs to be installed. I am afraid it won't work as a git submodule. what you can do is, create a fresh start with [this](https://github.com/zeon-studio/hugoplate?tab=readme-ov-file#-getting-started) process, and then copy your content folder from existing site, and paste here. it will be simpler. thanks
