### ISSUE TITLE
Language switcher disappears from the 404 page

### ISSUE THREAD

**Issue by ruskinik** [zeon-studio/hugoplate#85]
### What is your Hugo Extended Version

0.121.2

### What is your Go Version

1.21.5 darwin/arm64

### What is your Node.js Version

21.6.1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

Language switcher disappears when going to the 404 page or triggering the 404 error.

### Steps to Reproduce

From Pages menu item, follow 404 Page link or trigger the 404 error.

### Code Reproduction URL

github.com/ruskinik/hugoplate

**Comment by tfsomrat** [comment]
Hey @ruskinik, Hugo does not support language specific 404 page. but you can do some trick to translate 404 page content. checkout this post https://discourse.gohugo.io/t/how-to-translate-404-pages/41531
