### ISSUE TITLE
Cannot add comment in blog post

### ISSUE THREAD

**Issue by Dodero10** [zeon-studio/hugoplate#88]
### What is your Hugo Extended Version

v0.122.0

### What is your Go Version

go1.21.6 windows/amd64

### What is your Node.js Version

v20.11.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

I use discus to add comment. But I can't run it.

### Steps to Reproduce

1. Disqus seems to be taking longer than usual. [Reload](http://localhost:1313/blog/post-1/#)?
<img width="766" alt="Screenshot 2024-02-06 014730" src="https://github.com/zeon-studio/hugoplate/assets/111296775/bfe318fd-baa7-432d-bc83-2a1fe796663b">

**Comment by tfsomrat** [comment]
Hey @Dodero10, Disqus does not work on localhost. you need to deploy your project to use Disqus. thanks

**Comment by Dodero10** [comment]
![image](https://github.com/zeon-studio/hugoplate/assets/111296775/7585d29c-10dc-4f0c-9ee1-90842b7fbb6f)

I upload project to netlify but comment is not exist :(

**Comment by tfsomrat** [comment]
![image](https://github.com/zeon-studio/hugoplate/assets/58769763/b734c08f-99fd-494c-bfff-def6b09a1181)

I can see the Comments. I think your browser or the Internet has some issue with Disqus.

**Comment by Dodero10** [comment]
Thank you very much!!!
