### ISSUE TITLE
Partials not found on fresh install

### ISSUE THREAD

**Issue by dagoodma** [zeon-studio/hugoplate#9]
I just installed and launched hugoplate on a fresh site and I'm getting an error in hugo (Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z) on Ubuntu 20:

```
10:44 $ hugo server
Building sites … ERROR 2023/07/19 10:44:26 render of "taxonomyTerm" failed: execute of template failed: template: _default/terms.html:8:7: executing "_default/terms.html" at <partial "essentials/head.html" .>: error calling partial: "/home/dagoodma/Documents/davie-goodman-hugo-website/themes/hugoplate/layouts/partials/essentials/head.html:13:3": execute of template failed: template: partials/essentials/head.html:13:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: partial "favicon" not found
ERROR 2023/07/19 10:44:26 render of "taxonomyTerm" failed: execute of template failed: template: _default/terms.html:8:7: executing "_default/terms.html" at <partial "essentials/head.html" .>: error calling partial: "/home/dagoodma/Documents/davie-goodman-hugo-website/themes/hugoplate/layouts/partials/essentials/head.html:13:3": execute of template failed: template: partials/essentials/head.html:13:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: partial "favicon" not found
Built in 6 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:8:7: executing "index.html" at <partial "essentials/head.html" .>: error calling partial: "/home/dagoodma/Documents/davie-goodman-hugo-website/themes/hugoplate/layouts/partials/essentials/head.html:13:3": execute of template failed: template: partials/essentials/head.html:13:3: executing "partials/essentials/head.html" at <partialCached "favicon" .>: error calling partialCached: partial "favicon" not found
```

After commenting out the `{{ partialCached "favicon" . }}` stuff, then `{{ partialCached "manifest" . }}` and `{{ partialCached "site-verifications.html" . }}` start to throw the same error.

**Comment by dagoodma** [comment]
I read about using `npm run project-setup` and that cleared up this issue, but try as I might this theme is throwing tons of other errors: 
```
11:07 $ npm run dev

> hugoplate@1.5.2 dev
> hugo server

Built in 3 ms
Error: Error building site: "/home/dagoodma/Documents/davie-goodman-hugo-website/themes/hugoplate/content/english/sections/call-to-action.md:1:1": 1 error(s) decoding:

* cannot parse 'Render' as bool: strconv.ParseBool: parsing "never": invalid syntax
```
and then I comment out `_build:` and the everything below it, and another error appears:
```
11:07 $ hugo server
Built in 2 ms
Error: Error building site: "/home/dagoodma/Documents/davie-goodman-hugo-website/themes/hugoplate/content/english/pages/elements.md:10:1": failed to extract shortcode: template for shortcode "toc" not found
```

I'm just gonna move on and find another theme.

**Comment by tfsomrat** [comment]
Hey @dagoodma 

Sorry for the late reply. we clearly said in our readme file that this theme needs at least Hugo v0.115.1 extended. 
![image](https://github.com/zeon-studio/hugoplate/assets/58769763/cba6eeb1-eef3-41a1-afae-fb1e50310313)

And you are trying to run this theme using v0.68.3 extended. It will be never going to run. please install the latest Hugo, Go, and Node LTS to run this theme. thanks

**Comment by dagoodma** [comment]
Hi @tfsomrat! My bad on not checking the documentation better. I'm new to Hugo. I'll give it another try with the newer Hugo. Thanks!

**Comment by dagoodma** [comment]
I installed the extended version of Hugo v0.115.4 and retried this theme by first copying the example site and doing all of the recommended steps: `npm run project-setup`, `npm install`, `npm run build`. Those all worked (once I installed the extended version), but then running `hugo server` in the project root failed:
```bash
10:44 $ hugo server
Watching for changes in /home/dagoodma/Documents/davie-goodman-hugo-website2/{archetypes,assets,content,data,hugo_stats.json,i18n,layouts,postcss.config.js,static,tailwind.config.js}
Watching for config changes in /home/dagoodma/Documents/davie-goodman-hugo-website2/hugo.toml, /home/dagoodma/Documents/davie-goodman-hugo-website2/config/_default
Start building sites … 
hugo v0.115.4-dc9524521270f81d1c038ebbb200f0cfa3427cc5+extended linux/amd64 BuildDate=2023-07-20T06:49:57Z VendorInfo=gohugoio

Built in 843 ms
Error: error building site: POSTCSS: failed to transform "css/style.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/: binary with name "npx" not found
```

This looks like an issue related to me using `nvm`. I'm not sure how to proceed from here. Here's a git issue I found: https://github.com/gohugoio/hugo/issues/9730

Any ideas what to do next?

**Comment by tfsomrat** [comment]
It seems you messed up with the steps. not to worry! I have added a quick video in the readme file. take a look.
