### ISSUE TITLE
HTTP 404 not correctly mapped in Vercel

### ISSUE THREAD

**Issue by alexgutjahr** [zeon-studio/hugoplate#90]
### What is your Hugo Extended Version

hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended darwin/arm64 BuildDate=2024-01-26T15:54:24Z VendorInfo=brew

### What is your Go Version

go version go1.21.6 darwin/arm64

### What is your Node.js Version

v21.2.0

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

Deploying to Vercel with the provided `vercel.json` should make use of the provided `404.html` error page.
According to the [docs](https://vercel.com/guides/custom-404-page) the `404.html` in the build should be picked up automatically, but it seems that it is not.

### Steps to Reproduce

Deploy a fresh setup to Vercel.

### Additional Information

I have extended the config with an explicit mapping, which then worked.
If this is the desired approach I am happy to open a small PR.

```json
"routes": [
  { "handle": "filesystem" },
  { "src": "/(.*)", "status": 404, "dest": "/404.html" }
]
```

**Comment by tfsomrat** [comment]
Hey @alexgutjahr, thanks for noticing, it would be great if you make a PR.
