### ISSUE TITLE
IsHome does not return what is expected on the home page

### ISSUE THREAD

**Issue by ruskinik** [zeon-studio/hugoplate#92]
### What is your Hugo Extended Version

0.121.2

### What is your Go Version

1.21.5

### What is your Node.js Version

21.6.1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

`<p>IsHome: {{ .IsHome }}</p>` to return `true` on the home page. Right now it returns nothing. Tested on out of the box Hugoplate site (locally).

### Steps to Reproduce

In `layouts/index.html` insert:

`<p>IsHome: {{ .IsHome }}</p>`

Nothing is printed.

However:

```
{{ if not .IsHome }}
  <p>foo</p>
{{ end }}
```
on `themes/hugoplate/layouts/about/list.html` returns `foo`.

### Additional Information

I raised this on Hugo discourse, please [see my post](https://discourse.gohugo.io/t/ishome-function-doesnt-work-on-deployed-site/48183) for more details.

**Comment by ruskinik** [comment]
Further info (sanity check):

Deleting everything in `layouts/index.html` between `{{ define "main" }}` and `{{ end }}` and having: 

`<p>IsHome: {{ .IsHome }}</p>` 

prints `true` is expected.

**Comment by tfsomrat** [comment]
Hey @ruskinik, Hugo does not print `true` or `false` value. try run <p>IsHome: {{ if .IsHome }}true{{ else }}false{{ end }}</p>

**Comment by ruskinik** [comment]
Hi @tfsomrat, thanks for replying.

Hugo will print `true` if you delete everything between `{{ define "main" }}` and `{{ end }}` in `index.html`.

But that was simply a test.

The actual issue is this.

I was trying to call a partial in my `footer.html` with this code:

```
{{ if not .IsHome }}
  {{ partial "footer-top.html" . }}
{{ end }}
```

The idea being only having `footer-top.html` on all pages except home page.

It works on localhost but not when I deploy the site to Netlify, that is, `footer-top.html` shows up on the home page.

I tried changing `BaseURL` from `/` to the URL provided by Netlify. It didn't work. I tried deploying to a different service, same thing, so it's not Netlify causing this problem.

I tried something different. In `content/english/_index.md` I added `hideFooterTop: true` and in `footer.html`:

```
{{ if not .Params.hideFooterTop }}
  {{ partial "footer-top.html" . }}
{{ end }}
```

Again, it works on localhost but doesn't when I deploy the site to Netlify.

Trying to debug, I tried `<div>Current page URL: {{ .URL }}</div>` and `<div>Current page Permalink: {{ .Permalink }}</div>`. The `.URL` function failed the build, not sure if this is relevant, and `<div>Current page Permalink: {{ .Permalink }}</div>` printed nothing while `single.html` prints `//localhost:1313/foo/bar/` as expected.

**Comment by tfsomrat** [comment]
I think I got the issue. Footer partial is actually cached partial. open `baseof.html` and you will find it. you need to add your partial in `baseof.html` file before calling footer partial. or you need to replace `partialCached` with `partial` for footer.

**Comment by ruskinik** [comment]
Alright, no worries, I won't mess with caching. Instead I added `{{ partial "footer-top.html" . }}` to the `single.html` where I want that partial to show up. Didn't think of it before. Still on the learning curve.

Closing now.

Thanks for your help.
