### ISSUE TITLE
Nested Menu

### ISSUE THREAD

**Issue by ruskinik** [zeon-studio/hugoplate#95]
### What is your Hugo Extended Version

0.121.2

### What is your Go Version

1.21.5

### What is your Node.js Version

21.6.1

### Check for Existing Issues

- [X] I have searched and found no relevant issues.

### Expected Behavior

Hi guys. Is there a chance to build in a nested menu that goes down more than one level?

### Steps to Reproduce

Currently, we have:

```
[[main]]
name = "Solutions"
weight = 10
hasChildren = true

[[main]]
parent = "Solutions"
name = "Hybrid Cloud"
weight = 20
url = "solutions/hybrid-cloud"

[[main]]
parent = "Solutions"
name = "Cross Cloud"
weight = 30
url = "solutions/cross-cloud"
```
So far so good.

But if I add:

```
[[main]]
parent = "Solutions"
name = "Integrations"
weight = 40
hasChildren = true

[[main]]
parent = "Integrations"
name = "AWS"
weight = 1
url = "services/amazon-web-services"
```

This second level doesn't get rendered.

**Comment by tfsomrat** [comment]
Hey @ruskinik, Hugo does not support multi-level menu. But If you really need this, you can go with `params` instead of `menus`. we are available for hire. you can contact us for any customization at https://zeon.studio

**Comment by ruskinik** [comment]
Alright, thanks, will be in touch if we don't solve this ourselves.
