### ISSUE TITLE
More detailed documentation..

### ISSUE THREAD

**Issue by stefandolby** [zeon-studio/hugoplate#96]
Novice and just started out with Hugo and hugoplate. Love it. The install went flawlessly as went the basic config. But I bump into some issues when copying (demo) pages to reuse for different purposes. Is there more documentation (sorry couldn't find it) that explains how to add e.g. a blank static page and reuse elements from the demo pages? Thanks!

**Comment by TrogdorTheMan** [comment]
Agreed, I'd really like to see a bit more fleshed out documentation. Just following your steps and trying to the 'npm run dev' command results an a mess of warnings about templates, which is fine, but there is also an error right out of the gate about rendering short codes. Pretty difficult for noobs to parse.

`Error: Error building site: "/home/trogdor/websites/hugoplate/content/english/pages/elements.md:221:1": failed to render shortcode "gallery": failed to process shortcode: execute of template failed: template: shortcodes/gallery.html:31:11: executing "shortcodes/gallery.html" at <partial "image-pipe.html" (dict "Context" $scratch "Height" $height "Width" $width "Command" $command "Webp" $webp "Image" $image "Option" $option "Zoomable" $zoomable "Resize" $resize)>: error calling partial: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/gallery-slider@v0.0.0-20240215103202-c030d4222242/layouts/partials/image-pipe.html:39:22": execute of template failed: template: partials/image-pipe.html:39:22: executing "partials/image-pipe.html" at <add>: wrong number of args for add: want 2 got 3`

**Comment by tfsomrat** [comment]
Hey @stefandolby, Thanks for choosing Hugoplate. This is a boilerplate mostly build for developers. and they know how to deal with Hugo. So there is no specific detailed documentation for Hugoplate. But I can suggest you to checkout [Gethugothemes Hugo Guide](https://docs.gethugothemes.com/guide/) to get some basic knowledge. Thank you
