### ISSUE TITLE
single.html not rendering

### ISSUE THREAD

**Issue by ruskinik** [zeon-studio/hugoplate#97]
Created `layouts/foo/single.html`:

```
{{ define "main" }}
<p>This is a foo page</p>
{{ end }}
```
And `content/english/foo/index.md`:
```
---
title: "Foo page"
---
```
Going to `localhost:1313/foo` shows no content from `single.html`.

[Repo](https://github.com/ruskinik/hugoplate) and [GitHub build.](https://ruskinik.github.io/hugoplate/)

**Comment by tfsomrat** [comment]
But I can see your Foo page https://ruskinik.github.io/hugoplate/foo/

**Comment by ruskinik** [comment]
It's missing `<p>This is a foo page</p>` though which means none of the html in `single.html` will be rendered, no?

**Comment by tfsomrat** [comment]
It should work, but somehow it's not working. and it's not the issue of this theme. you can try any theme or create a new theme by `hugo new theme theme-name` and you will get the same result. 

what you can do is to create a `layouts/foo/list.html` file and `content/foo/_index.md` file, and you will get your expected result.
